### ISSUE TITLE
Troubles running your example code

### ISSUE THREAD

**Issue by mmazloum** [edcarroll/ng2-semantic-ui#1]
Hi,

I'm trying to use your components (thanks for the job), the project I'm coding uses nodeJS 6 and Angular 2 beta 15. Everything seems to work fine until I call the directive sui-checkbox, then I get this error : 

![image](https://cloud.githubusercontent.com/assets/3626499/14877821/c676b3d2-0d1f-11e6-9d72-fe71c2d1c194.png)

Any Idea of what's wrong ?

**Comment by edcarroll** [comment]
Hey, I have had a play and it appears the minified build was causing the issue. I have turned mangling off when making the bundle and have released a fixed version - if you update to v0.2.2 you should be able to continue with the minified build.

**Comment by mmazloum** [comment]
Thanks a lot it works ;-) I'll play with your other directives.
