### ISSUE TITLE
Problem with mustScroll in Modal

### ISSUE THREAD

**Issue by yavorskiy-web** [edcarroll/ng2-semantic-ui#104]
According to the docs try set mustScroll property, but get an error:

**Error:** Property 'mustScroll' does not exist on type 'ConfirmModal'

```
export class ConfirmModal extends ComponentModalConfig<IConfirmModalContext, void, void> {
    constructor(title:string, question:string) {
        super(ModalInvoiceComponent, { title, question });

        this.isClosable = true;
        this.transitionDuration = 200;
        this.size = ModalSize.Small;
        this.mustScroll = true;
    }
}
```

![screenshot](https://user-images.githubusercontent.com/19890852/26867401-d998bcac-4b6d-11e7-9788-6e39115dab92.jpg)

**Comment by edcarroll** [comment]
I've just tested this in a brand new repo, and I can't reproduce the same error - could you double check you're on `^0.8.1`, and reload your type definitions as well please?

**Comment by yavorskiy-web** [comment]
I tried this functionality in a new project - everything works fine. The problem was in type definitions. Sorry )
