### ISSUE TITLE
Tabs overflowing the segment they are attached to.

### ISSUE THREAD

**Issue by GuillemPallares** [edcarroll/ng2-semantic-ui#115]
I'm adding dynamic created tabs to my porject, and when the number of tabs is big enough, the tabs headers overflow the segment they are attached to, and go offsrcreen.

By now, my current solution is that I limited the number of tabs I can create, depending on the screen resolution.

Is there any type of scrolling component that can be added to the tab header or a solution that doesn't need to limit the number of tabs?

**Comment by edcarroll** [comment]
Unfortunately, Semantic UI doesn't provide support for tab overflow out of the box, so this can't easily be done without me adding extra CSS to the library, which isn't a good idea due to themeing etc.

One option is to use a tabs menu:

```html
<sui-tabset>
        <div class="ui three wide stackable tabs menu">
            <a class="item" suiTabHeader="auto">Automatic</a>
            <a class="item" suiTabHeader="template">Template Based</a>
            <a class="item" suiTabHeader="component">Component Based</a>
        </div>

        <div class="ui segment" suiTabContent="auto">...</div>        <div class="ui segment" suiTabContent="auto">...</div>

**Comment by GuillemPallares** [comment]
Lots of thanks!
