### ISSUE TITLE
Select dropdown with [isSearchable]=true not closing when caret is clicked.

### ISSUE THREAD

**Issue by jmozqueda1** [edcarroll/ng2-semantic-ui#118]
### Bug description:

Not able to close a sui-select or sui-multi-select when the [isSearchable]=true. My thinking was that I should be able to click on the caret for the dropdown to collapse instead of having to click on another part of the page since there could be additional items that would be hiding behind the dropdown.  This can be recreated with the current demo. 

### Version of ng2-semantic-ui:

ng2-semantic-ui: 0.8.3

**Comment by edcarroll** [comment]
Hi there, good catch, and I can see what you mean. Will add a fix to make clicking the caret close all dropdowns to the next release :)

**Comment by jmozqueda1** [comment]
Awesome. Thank you!

**Comment by edcarroll** [comment]
A fix for this is now live in `0.8.4` 😄

**Comment by jmozqueda1** [comment]
Thanks for the quick fix!
