### ISSUE TITLE
ng2-semantic-ui modal not working in ie browser

### ISSUE THREAD

**Issue by kalai4013** [edcarroll/ng2-semantic-ui#120]
ng2 semantic ui modal not working in IE browser

        <sui-modal [isClosable]="true" (dismissed)="alert($event)" #modal>
        <div class="header">Example</div>
        <div class="content">
        <p>Modal content</p>
        </div>
        <div class="actions">
        <button class="ui red button" (click)="modal.deny()">Cancel</button>
        <button class="ui green button" (click)="modal.approve('done')">OK</button>
         </div>
       </sui-modal>

      not working.

        Error: 
                 ERRORTypeError: Object doesn't support property or method 'remove' 

        Angular cli versions:
          dependencies": {
               "@angular/animations": "^4.2.2",
               "@angular/common": "^4.2.2",
               "@angular/compiler": "^4.2.2",
                "@angular/compiler-cli": "^4.2.2",
               "@angular/core": "^4.2.2",
              "@angular/forms": "^4.2.2",
               "@angular/http": "^4.2.2",
              "@angular/platform-browser": "^4.2.2",
              "@angular/platform-browser-dynamic": "^4.2.2",
              "@angular/platform-server": "^4.2.2",
             "@angular/router": "^4.2.2",
             "core-js": "^2.4.1",
             "rxjs": "^5.1.0",
             "typescript": "^2.3.4",
             "zone.js": "^0.8.4"

**Comment by edcarroll** [comment]
Hi, thanks for pointing this out. Will get a fix out for this ASAP.

**Comment by edcarroll** [comment]
A fix for this is now live in `0.8.4` 😄

**Comment by kalai4013** [comment]
Thank you. its working fine...It working on IE10 and IE11.
