### ISSUE TITLE
Scrolling modals not correctly aligned

### ISSUE THREAD

**Issue by trevordaniels** [edcarroll/ng2-semantic-ui#126]
### Bug description:
Two layout issues with scrolling modals;
- Full screen modal loses its center alignment 
- A modal does not have its own scrolling context, but instead relies on the underlying page. Therefore a scrolled page will not show its modal aligned within the visible window, but potentially out of sight at the top of the underlying page. Semantic UI creates a scrolling context based on the height of the modal, independent of the underlying page height. 

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/kie6w2dnvVhuzbJ9jFvk?p=preview

**Comment by edcarroll** [comment]
Thanks for the issue report & repro. Can see what you mean for both, and will get them sorted for the next release in a couple of days.

**Comment by edcarroll** [comment]
This is now live in `0.9.0` :smile:

**Comment by ImTheC** [comment]
Note: If wanting to use `config.isFullScreen = true;` don't also specify a size with `config.size = <size>`, otherwise the modal loses its center alignment again.

**Comment by trevordaniels** [comment]
The problem with the scrolling context looks like it is still happening. The modal can appear partially or completely hidden at the top of screen, depending on where the page is scrolled. Seems to happen if the modal is fullscreen or not.

**Comment by trevordaniels** [comment]
Is it possible to get this issue re-opened?

**Comment by edcarroll** [comment]
Yep, missed your comment, sorry!

**Comment by harogaston** [comment]
I couldn't reproduce the original Plunker issue anymore in current version. Is there any _working_ example of the new problem reported by @trevordaniels ?

**Comment by harogaston** [comment]
> Note: If wanting to use config.isFullScreen = true; don't also specify a size with config.size = <size>, otherwise the modal loses its center alignment again.

@ImTheC that appears to be broken upstream (Semantic UI), we could try reporting it. Or maybe it is _a feature_.

**Comment by trevordaniels** [comment]
@harogaston Alignment issues still occur for me in the original plunkr, dependant on browser width. 

With a narrower window the scroll height correctly adjusts to match the height of the modal, however the initial scroll position is midway down the page. Ideally it should scroll to the top in this case.

![image](https://user-images.githubusercontent.com/459107/28699329-5579c438-738c-11e7-8665-b326a0317c17.png)

With a wider window, the scroll height does not adjust to suit the height of the modal. The modal appears top aligned and the scroll position is unchanged leaving the modal potentially partly or fully hidden.

![image](https://user-images.githubusercontent.com/459107/28699428-ef33a224-738c-11e7-88f3-09a6e470e53b.png)

**Comment by harogaston** [comment]
Sorry for the late reply @trevordaniels . What I really meant was that your plunker code works OK if I try it on the test page ([demo/src/app/pages/development/test/test.page.html](https://github.com/edcarroll/ng2-semantic-ui/blob/master/demo/src/app/pages/development/test/test.page.html)). 

Nevertheless I am aware that your plunker code doesn't work in Plunker itself. I am not sure how to interpret these results. 

Could it be that Plunker does some strange behind the scenes that is causing this? Could the Plunker be using different versions of anything (Angular, Semantic, etc.)? I don't know.

**Comment by trevordaniels** [comment]
I've tested this and you are right @harogaston the issue seems to be related to plunkr itself. Happy for this to be closed, thanks for looking into it.

**Comment by harogaston** [comment]
Perfect @trevordaniels . Keep us posted and we can surely work that out.

**Comment by trevordaniels** [comment]
To reproduce in test page;
1. remove pushable class from sui-sidebar-container
2. remove position:fixed from demo-root element

**Comment by edcarroll** [comment]
@trevordaniels thank you for the easy repro in the demo app. Have just opened a PR that fixes this - modals now live inside the dimmer that opens with them, and since it is a page dimmer it gets position fixed and scrolling without any difficulties. Will be pushed out in the next release 😄

**Comment by edcarroll** [comment]
Finally got this sorted, and it's now live in `0.9.5`. Let me know if something else comes up though!
