### ISSUE TITLE
keyboard behavior for sui-select is not as framework nor standard html

### ISSUE THREAD

**Issue by genuinefafa** [edcarroll/ng2-semantic-ui#128]
### Bug description:

When using `<sui-select>` up/down arrows of keyboard do not respond to keypress. In the current version it just fallback to browser behavior (move scroll of page in my machine).

The desired behavior, and the one from the framework (and html standard), is to open the select options when **downarrow** key is pressed on keyboard.

### Demo links:

 * [ng2-semantic-ui select](https://edcarroll.github.io/ng2-semantic-ui/#/components/select)
 * [dropdown semantic ui - base framework](https://semantic-ui.com/modules/dropdown.html)

### Version of Angular, ng2-semantic-ui, and Semantic UI:

Angular: 4.1.3
ng2-semantic-ui: 0.8.4
Semantic UI: 2.2.10

**Comment by edcarroll** [comment]
I see the issue, will get a fix for this out in the next release 😄

**Comment by edcarroll** [comment]
In a similar vein to this, I've also added full tab support to this branch for the dropdown, search & select components. This means, as in Semantic UI, it is possible to tab between these components (as in `tab` and `shift+tab`) and they'll automatically open and close as they gain and lose focus.

**Comment by edcarroll** [comment]
This is now live in `0.9.0` :smile:
