### ISSUE TITLE
Add support for ng-template in sui-search.

### ISSUE THREAD

**Issue by craig-gaskill** [edcarroll/ng2-semantic-ui#136]
### Feature description:

Add support for `ng-template` in the `sui-search` component (similar to the `sui-select` component) so we can provide results with more context. 

### Version of Angular, ng2-semantic-ui, and Semantic UI:

Angular: 4.2.4

ng2-semantic-ui: 0.8.4

Semantic UI: 2.2.10

**Comment by edcarroll** [comment]
`0.9.0` will bring support for this functionality :)

**Comment by edcarroll** [comment]
This is now live in `0.9.0` :smile:
