### ISSUE TITLE
feat(select): support custom search function

### ISSUE THREAD

**Issue by genuinefafa** [edcarroll/ng2-semantic-ui#137]
### Description:

`<sui-select` component do not allow customization for the search/filter function, it will always search the containing text and that's not always the best case. Let's say that you have

 * this is
 * a test
 * this test
 * here is a test

I wanna allow my user to search by using _here test_ and the only result being _here is a test_.

### Link to minimally-working plunker that reproduces the issue:
no need

### Versions:

Angular: 4.1.3
ng2-semantic-ui: 0.8.4
Semantic UI: 2.2.10

**Comment by edcarroll** [comment]
This is now live in `0.9.0` :smile:
