### ISSUE TITLE
Unexpected value 'SuiModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by csepmdat** [edcarroll/ng2-semantic-ui#14]
I have follow the instruction and I got this error when trying to import SuiModue to AppModule. Please show me how to resolve this.  And I am using `angular2-webpack-starter`.

`Unexpected value 'SuiModule' imported by the module 'AppModule'`

Thanks.

**Comment by edcarroll** [comment]
This should now be fixed in 0.3.4 - let me know if you have any further issues! :)

**Comment by csepmdat** [comment]
It's worked. Thank you so much.
