### ISSUE TITLE
feat: Add autofocus support to dynamic components (popup, modal)

### ISSUE THREAD

**Issue by santha6693** [edcarroll/ng2-semantic-ui#142]
AutoFocus is Not Working in Ng2 Semantic ui Modal.

<ng-template let-context let-modal="modal" #modalTemplate>
    <div class="header">Example</div>
    <div class="content">
        <input type="text" autofocus/>
    </div>
    <div class="actions">
        <button class="ui red button" (click)="modal.deny('denied')">Cancel</button>
        <button class="ui green button" (click)="modal.approve('approved')">OK</button>
    </div>
</ng-template>

**Comment by edcarroll** [comment]
Hi there, in order to help you I need to see a reproduction scenario in plunkr, as the issue template suggests. Please make one and comment it here and I can try to help out.

**Comment by santha6693** [comment]
I want to Display a form in Modal but when Opening the Modal the Focus is not Automatically Set to the First Text Box Even When I gave autofocus also.Please let me Know How to Set the Focus in TextBox when Opening Modal itself.

**Comment by edcarroll** [comment]
How are you opening the modal, is it using a template, component, or just automatically?

**Comment by santha6693** [comment]
By Using Template.

**Comment by edcarroll** [comment]
So I've had a think and the only way to do this outside of the library is going to be less than ideal, so I'm going to add a feature in the `0.9.0` release that focusses any element inside the template that has the autofocus attribute automatically on open :)

**Comment by santha6693** [comment]
can I know when the 0.9.0 version will release.

**Comment by edcarroll** [comment]
Very soon

**Comment by edcarroll** [comment]
This is now live in `0.9.0` :smile:

**Comment by santha6693** [comment]
Thank You,The Autofocus was working fine in Chrome and Firefox But it was not working in Internet Explorer.

**Comment by edcarroll** [comment]
Sorry, to clarify do you mean it wasn't working and now it is, or that it currently isn't working?

**Comment by santha6693** [comment]
Currently it was not working in IE .

**Comment by edcarroll** [comment]
Ok I've tested it in IE11 and can see it isn't working - apologies, I was getting confused by the 2 different tenses. I'm not quite sure why, but I'll open a new bug to track it.
