### ISSUE TITLE
bug: sui-select does not receive ngModel updates

### ISSUE THREAD

**Issue by dirkraft** [edcarroll/ng2-semantic-ui#143]
Here's a quick plnkr: http://plnkr.co/edit/RWdFTx?p=preview

I expect the select to show the value bound by ngModel ("purple"). Instead the select is blank. Maybe I am doing something wrong.

**Comment by edcarroll** [comment]
This is a tough one, as writing the select options this way means that the select component doesn't know in advance what options are available (currently by design). However, it makes sense that this should work, so will mark this as a bug and get a fix out in the next release :)

**Comment by edcarroll** [comment]
This is now live in `0.9.0` :smile:

**Comment by dirkraft** [comment]
yeessssss 🎉 thanks!

**Comment by edcarroll** [comment]
You're very welcome 😄
