### ISSUE TITLE
Q: How to use components in app-components?

### ISSUE THREAD

**Issue by Gmentsik** [edcarroll/ng2-semantic-ui#144]
Sorry if this question is not an issue with this project and more a general question to angular. 

How can I access the components from within my app-components.

So let's say I want to activate a suiTab that is inside page1.component.html from a method that is inside page1.component.ts ?

Another example would be:
How can I toggle the sidebar from withing a method?

The documentation just uses the HTML attributes for this and there are no examples for the Typescript part.

Thanks!

**Comment by edcarroll** [comment]
The way you control things from typescript here is by setting the boolean values in your code, so for example in a sidebar you would put:

```html
<sui-sidebar-container class="ui bottom attached segment">
    <sui-sidebar class="inverted vertical" [(isVisible)]="sidebarVisible">
        <a class="item">1</a>
        <a class="item">2</a>
    </sui-sidebar>
    <sui-sidebar-sibling [isDimmedWhenVisible]="true">
        <div class="ui basic segment">
            <h3 class="ui header">Content</h3>
            <button class="ui button" (click)="openSidebar()">Open Sidebar</button>
        </div>
    </sui-sidebar-sibling>
</sui-sidebar-container>
```

then in Typescript:

```typescript
@Component({})
export class MyComponent {
    public sidebarVisible:boolean = false;

    public openSidebar():void {
        sidebarVisible = true;
    }
}
```

Which will open the sidebar whenever you click the button.

This way, you can get all the functionality you need via the HTML attributes.

Does this help?

Addendum: The way you would directly control the components (and have access to their classes) is by tagging them with a variable name (`#tab`) then using `@ViewChild` to access it and control it. However, that isn't the best way to do things, and something that I've avoided as much as possible in the library.

**Comment by Gmentsik** [comment]
Thank you very much, I was using {{var}} which of course did not work. This is working as expected!

**Comment by edcarroll** [comment]
Glad I could help 😄
