### ISSUE TITLE
bug(select): Search is not filtering results in multi-select

### ISSUE THREAD

**Issue by ericwyh** [edcarroll/ng2-semantic-ui#149]
### Bug description:
When searching options in sui-multi-select, the options are not filtered at all.
Only part that seems to behave correctly is if the search param doesn't match any options, it will still display 'No results'. 

Please let me know if I'm doing something wrong. 

### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/fbrOoP?p=preview

### Version of Angular, ng2-semantic-ui, and Semantic UI:
ng2-semantic-ui: 0.8.4

**Comment by edcarroll** [comment]
See my answer to #148
