### ISSUE TITLE
Input components not syncing with reactive forms validation

### ISSUE THREAD

**Issue by trevordaniels** [edcarroll/ng2-semantic-ui#155]
sui-select and sui-checkbox dont seem to be in sync with angular validation classes when using reactive forms.

eg. After clicking on a Checkbox component, the sui-checkbox element does not update its class to ng-touched, whereas the inner input element does. Conversely, the outer element handles dirty/pristine and valid/invalid correctly whereas the inner element does not.

http://plnkr.co/edit/u8FrRU77lZ0l3Ss0BUeB

**Comment by edcarroll** [comment]
`0.9.2` has just gone live, which adds full `ng-touched` support to the checkbox, select & datepicker components.

The checkbox specifically now only gains `ng-touched` when focus is lost.
