### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError for SuiAccordionPanel.html

### ISSUE THREAD

**Issue by JiJongLo** [edcarroll/ng2-semantic-ui#158]
### Version of Angular, ng2-semantic-ui, and Semantic UI:

Angular: 4.2.5

ng2-semantic-ui: 0.9.1

Semantic UI: none

**Comment by edcarroll** [comment]
The fix for this will go live soon

**Comment by edcarroll** [comment]
Fix is now live in `0.9.2` 😄
