### ISSUE TITLE
it does not work after select a item

### ISSUE THREAD

**Issue by ppneo007** [edcarroll/ng2-semantic-ui#163]
html file: 
<sui-search placeholder="Example Search..."
            [hasIcon]="hasIcon"
            [options]="options"
            [searchDelay]="0"
            (resultSelected)="alertSelected($event)">
</sui-search>

ts file:
    public alertSelected(selectedItem:string):void {
        alert(selectedItem);
    }

------did I forgot something??

**Comment by edcarroll** [comment]
Sorry, without a reproduction in plunkr I can't help you.

You can fork [this base plunkr](http://plnkr.co/edit/SJMMMS8wQkwdX1HeMqiH?p=preview) as a starting point.

**Comment by ppneo007** [comment]
I got it!! It's an old version in my app(0.8.4). Everything is fine after uptating to  0.9.2 !

anyhow thanks!

**Comment by edcarroll** [comment]
No problem, glad you got it sorted!
