### ISSUE TITLE
Allow 12-hour time selection option for time picker

### ISSUE THREAD

**Issue by jmozqueda1** [edcarroll/ng2-semantic-ui#164]
Requesting an enhancement to have an option for the time picker to display a 12-hour selection (with AM and PM) instead of the 24-hour international version.

**Comment by edcarroll** [comment]
Hi there, to clarify, do you mean when selecting a date?

**Comment by jmozqueda1** [comment]
The time selection. Right now the selection is based on 00:00-23:55. For example, some countries like the time to be 12:00 AM instead of 00:00 and 2:00 PM instead of 14:00 :).

**Comment by harogaston** [comment]
I can work this out!

**Comment by edcarroll** [comment]
This is now merged into master and will be released in `0.9.5`, thanks to @harogaston 😄 Whether or not 12 hour clocks are used is defined by the locale you choose.
