### ISSUE TITLE
Error After Updating ng2-semantic-ui

### ISSUE THREAD

**Issue by santha6693** [edcarroll/ng2-semantic-ui#166]
After Updating the ng2-semantic-ui .I got Below Error.

ERROR in D:/Angualr4.2/RDS/node_modules/ng2-semantic-ui/dist/modules/popup/classes/popup-controller.d.ts (11,31): Type 'SuiPopupController' has no properties in common with type 'IPopupLifecycle'.

**Comment by yavorskiy-web** [comment]
Сonfirm, I have the same error.

**Comment by edcarroll** [comment]
I believe this is due to Typescript 2.4.1 - the library doesn't yet support versions over ~2.3. Could you try downgrading and see if it is resolved?

**Comment by Meshkati** [comment]
After the update, I got many errors about TS files too.

I'm on TSC 2.3.2

**Comment by edcarroll** [comment]
@Meshkati did you get the same error regarding the popup component?

**Comment by edcarroll** [comment]
@yavorskiy-web, @santha6693 if you can confirm this is a Typescript 2.4 issue I can get a fix out for it tomorrow 😄 otherwise it will be a while as I'm going away for a week

**Comment by yavorskiy-web** [comment]
I will downgrade ts tommorow. Sorry for delay :)
I will write the result necessarily.

**Comment by Meshkati** [comment]
@edcarroll I get errors about popup, datepicker and modals classes !!!

**Comment by edcarroll** [comment]
@Meshkati what are the errors?

**Comment by Meshkati** [comment]
ERROR in /Users/invisible/Documents/questionAnsweringService/node_modules/ng2-semantic-ui/dist/modules/datepicker/classes/calendar-mappings.d.ts (2,39): ',' expected.

ERROR in /Users/invisible/Documents/questionAnsweringService/node_modules/ng2-semantic-ui/dist/modules/datepicker/classes/calendar-mappings.d.ts (6,14): Generic type 'Calen
darMapping' requires 2 type argument(s).

**Comment by edcarroll** [comment]
You need to update to Typescript 2.3, currently you're on a version below that (2.3 introduces support for default generic types which is what is causing the compile errors in your build).

**Comment by santha6693** [comment]
@edcarroll . My Typescript version is 2.4.1. I think this might cause issue, since i updated my tsc version yesterday from then it's not working. Before updating the version it was working fine for me. It wil be helpful if you fix it :) Thanks

**Comment by santha6693** [comment]
Please find my module versions in package.json for reference,

"dependencies": {
    "@angular/animations": "^4.2.5",
    "@angular/common": "^4.2.5",
    "@angular/compiler": "^4.2.5",
    "@angular/compiler-cli": "^4.2.5",
    "@angular/core": "^4.2.5",
    "@angular/forms": "^4.2.5",
    "@angular/http": "^4.2.5",
    "@angular/platform-browser": "^4.2.5",
    "@angular/platform-browser-dynamic": "^4.2.5",
    "@angular/platform-server": "^4.2.5",
    "@angular/router": "^4.2.5",
    "core-js": "^2.4.1",
    "mydatepicker": "^2.0.22",
    "ng-semantic": "^1.1.13",
    "ng2-toastr": "^4.1.2",
    "ngx-barcode": "^0.2.2",
    "rxjs": "^5.1.0",
    "semantic-ui": "^2.2.10",
    "typescript": "^2.4.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.2.0",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }

**Comment by yavorskiy-web** [comment]
@edcarroll I downgrode ts 2.4.1 to 2.3.0 and all works fine for me. The problem clearly in version of ts )

**Comment by santha6693** [comment]
@edcarroll I have also downgraded to 2.3.2. Its working fine. The problem is definitely with the TSC version. :)

**Comment by edcarroll** [comment]
An update on this - I've fixed the error so that it no longer throws using TS 2.4.1, but the library itself hasn't moved onto the new TS, because it compiles in strict mode, which Angular currently doesn't support with the newer Typescript. However, if you're not using strict mode in your projects it all should now work fine.

Update to `0.9.3` to get this fix, and let me know if something still isn't working in TS 2.4

**Comment by thatham** [comment]
@edcarroll My Typescript version is 2.4.2 and angular version is 5.0.2. I'm receiving below error while debugging.

Exception has occurred: Error
Error: Can't resolve all parameters for SuiComponentFactory: (?, ?, ?).
at syntaxError (~\node_modules\@angular\compiler\esm2015\compiler.js:431:24)
at CompileMetadataResolver._getDependenciesMetadata (~\node_modules\@angular\compiler\esm2015\compiler.js:12960:1)
at CompileMetadataResolver._getTypeMetadata (~\node_modules\@angular\compiler\esm2015\compiler.js:12831:1)
at CompileMetadataResolver._getInjectableMetadata (~\node_modules\@angular\compiler\esm2015\compiler.js:12819:1)
at CompileMetadataResolver.getProviderMetadata (~\node_modules\@angular\compiler\esm2015\compiler.js:13104:1)
at providers.forEach (~\node_modules\@angular\compiler\esm2015\compiler.js:13032:1)
at Array.forEach (<anonymous>)
at CompileMetadataResolver._getProvidersMetadata (~\node_modules\@angular\compiler\esm2015\compiler.js:12992:1)
at CompileMetadataResolver.getNgModuleMetadata (~\node_modules\@angular\compiler\esm2015\compiler.js:12655:1)
at CompileMetadataResolver.getNgModuleSummary (~\node_modules\@angular\compiler\esm2015\compiler.js:12495:32)
