### ISSUE TITLE
Active new dynamic tab

### ISSUE THREAD

**Issue by csepmdat** [edcarroll/ng2-semantic-ui#17]
Hi all,

Is there anyway to active a new tab when it's created? 

I am using one static tab and a list of dynamic tab, when I push a new tab to the list, it should be active, I tried to used [isActive] but is went to an error with activeClosestTab. I guess this function run before the tab is append to the tab list so the error was raised.

Thanks.

**Comment by edcarroll** [comment]
Hi! Could you please setup a plunkr demonstrating what you're trying to do so I can investigate further?
Thanks :)

**Comment by edcarroll** [comment]
I've investigated myself a bit further, and have updated the tab activation logic.

Download v0.4.2, and try the following:

```html
<sui-tabset>
    <div class="ui top attached tabular menu">
        <a class="item" *ngFor="let tab of tabs; let i = index" [suiTabHeader]="i" [(isActive)]="tab.active">
            {{ tab.header }}
        </a>
    </div>
    <div class="ui bottom attached segment" *ngFor="let tab of tabs; let i = index" [suiTabContent]="i">
         {{ tab.content }}
    </div>
</sui-tabset>
```

If you use `[(isActive)]` and set the new tab's active property (or any boolean property linked to that tab) to `true` the tab will auto activate when added.

Let me know if you have any further issues or can't get this working!

**Comment by csepmdat** [comment]
Thanks you.
It worked like a charm.
