### ISSUE TITLE
Question: Use of sidebar without sui-sidebar-container and sui-sidebar-sibling

### ISSUE THREAD

**Issue by sumitridhal** [edcarroll/ng2-semantic-ui#172]
Is there any way i can use sidebar component separately without `sui-sidebar-container` and `sui-sidebar-sibling`?

**Comment by edcarroll** [comment]
What exactly are you meaning by this? Are you meaning to be able to create a sidebar component that you can include as a standalone element? - In that case, take a look at #89 for an example of that.

I hope that's what you were asking - if not, let me know 😄

**Comment by sumitridhal** [comment]
Thanks @edcarroll I was looking for the same; to create a separate component for sidebar.

**Comment by edcarroll** [comment]
Glad you got it sorted 😄
