### ISSUE TITLE
bug(select): not showing option = zero

### ISSUE THREAD

**Issue by trevordaniels** [edcarroll/ng2-semantic-ui#175]
Select control not showing option if option = 0

http://plnkr.co/edit/apyeP0w82w0VHh6fmFg2?p=preview

**Comment by edcarroll** [comment]
Not sure how this one has slipped through the cracks! Will address it in the next couple of days 😄

**Comment by edcarroll** [comment]
Have made a PR with a fix for this that will be released in an hour or so. Turned out there were a couple of falsiness related bugs in the select that have been sorted.

**Comment by edcarroll** [comment]
`0.9.3` is now live with a fix for this 😄
