### ISSUE TITLE
fix(modal): modal reappears when navigating away on modal dismiss

### ISSUE THREAD

**Issue by trevordaniels** [edcarroll/ng2-semantic-ui#186]
When navigating to a different route after dismissal of a modal, the modal begins to close but then re-appears after navigation.

http://plnkr.co/edit/XkkY2bWgrUSe51j17pYh

**Comment by edcarroll** [comment]
I see the issue here, this is because the modal moves itself outside of the app context in order to ensure styling works correctly. I'll make it so that it puts itself back after being dismissed, but before firing dismiss.

**Comment by edcarroll** [comment]
This is now live in `0.9.5`. Let me know if you have any further issues 😄

**Comment by nilesh-more** [comment]
@edcarroll still i'm  facing the same issue
