### ISSUE TITLE
Select component document is not right

### ISSUE THREAD

**Issue by csepmdat** [edcarroll/ng2-semantic-ui#19]
Hello @edcarroll 

I have found a small problem in the document at the events section.
http://edcarroll.github.io/ng2-semantic-ui/#/components/select 

It has to be `selectedOptionsChange` not `selectedOptionChange` like now.

It took me a while to look at the source code and found that missing `s` letter.

Please update for later used.

**Comment by edcarroll** [comment]
Hey, Good spot! Just updated the docs to reflect this. Thanks :smile:

**Comment by levivm** [comment]
@ivivivn @edcarroll 
For me is working using `selectedOptionChange` not `selectedOptionsChange`
