### ISSUE TITLE
bug(message): icon does not display correctly relative to content

### ISSUE THREAD

**Issue by trevordaniels** [edcarroll/ng2-semantic-ui#192]
If an icon is included in a message, it displays top centered instead of middle left aligned. Seems to be caused by .transition.visible classes on the message element overwriting display:flex with display:block 

http://plnkr.co/edit/iirQTgfM5PlHGpgTis55

**Comment by edcarroll** [comment]
I see the issue here. I'll add a setting to the transition component that allows you to disable the visibility class being set, that should resolve this.

**Comment by edcarroll** [comment]
This is now live in `0.9.5`. Let me know if you have any further issues 😄
