### ISSUE TITLE
bug(popup): lots of popups on a page degrade performance

### ISSUE THREAD

**Issue by trevordaniels** [edcarroll/ng2-semantic-ui#194]
This may well not be an issue with the library but thought I'd raise an issue in case there was an easy win to improve performance. I have a complex form with about 150 controls, each with a sui popup that displays when control is invalid. WIthout the popups added, the form is quick and responsive to all user interaction. But with the popups, it gets sluggish on all user interaction with noticeable delays for eg. on clicking checkboxes, selects, text fields etc. Does not seem related to trigger mode or activation of popups.

http://plnkr.co/edit/Vs1ymqcMRjNHE3cERdED

**Comment by edcarroll** [comment]
It's certainly very strange, as the popups seem to open immediately, but the components they're applied to get the laggy input.

I'll investigate this properly in a few days when I have some more time, hope that's ok.

**Comment by trevordaniels** [comment]
Thanks, that's fine. I'll investigate further as well.

**Comment by trevordaniels** [comment]
Looks like this document click handler is causing the lag when clicking anywhere on the page

https://github.com/edcarroll/ng2-semantic-ui/blob/master/src/modules/popup/classes/popup-controller.ts#L145

**Comment by edcarroll** [comment]
Ah I see what's happened. The reason this doesn't check to see if the popup is open before running the expensive contains function is because the popups used to only have a component ref when they were open. With the advent of the datepicker that needed to change to make state handling not horrific, but I didn't think to update the click handler.

Will add an open check to the next release to sort this out.

Thank you for investigating!! 🎉

**Comment by trevordaniels** [comment]
Unfortunately its not the body of the handler function but the presence of the handler itself causing the delay. Is it possible to only hook up this handler when a popup is opened?

**Comment by edcarroll** [comment]
I see - that's certainly something that can be done. `Renderer2` exposes listening functionality so I can hook it up when the popup opens and then remove it once it closes.

**Comment by trevordaniels** [comment]
This is definitely more of an issue in dev mode rather than prod. For my use case in prod mode the delay is negligible.

**Comment by edcarroll** [comment]
This is now live in `0.9.5`. Let me know if you have any further issues 😄

**Comment by aligorji** [comment]
This problem still exists
For example on the following page
https://edcarroll.github.io/ng2-semantic-ui/#/modules/popup
In first example
Displaying and hiding popup after about 100 times! (fast hover on button) causes the screen to become extremely slow (even scrolling page is difficult)
Until the page is reload
