### ISSUE TITLE
Popper.js error

### ISSUE THREAD

**Issue by mvcoding** [edcarroll/ng2-semantic-ui#195]
### Bug description:
Getting this error when i want to serve my app with ng2-semantic-ui included:

`node_modules/@types/popper.js/index.d.ts (104,3): Cannot redeclare exported variable 'default'.`
`node_modules/popper.js/index.d.ts (106,24): Cannot redeclare exported variable 'default'`

It seems to be related to the recent popper.js update 1.11.0, specifically the addition of types to their package with the pull [#351](https://github.com/FezVrasta/popper.js/pull/351). Manually downgrading popper.js to the older 1.10 branch temporarily helps to avoid the error.

### Version of Angular, ng2-semantic-ui, and Semantic UI:
- Angular: 4.3.1
- ng2-semantic-ui: 0.9.3
- Semantic UI: 2.2.11

**Comment by FezVrasta** [comment]
Is this a problem with the type definitions shipped with Popper.js or with the way the lib is used in this repo?

**Comment by mvcoding** [comment]
I think it's the latter. @types/popper.js is set as dependency in this repo which should cause the error.

**Comment by edcarroll** [comment]
Ahh ok I see whats happened. I'll now that Popper.js is including their own types I no longer need to depend on `@types/popper.js`. FYI the reason it's a dependency is because I re-export a couple of definitions from the lib hence the error. Will get a fix out in the next release.

**Comment by edcarroll** [comment]
Workaround for now is manually installing `popper.js@1.10.8`

**Comment by edcarroll** [comment]
As this is affecting quite a few people, I'm going to release a hotfix for it ASAP.

**Comment by FezVrasta** [comment]
@edcarroll what could have been done on Popper.js side to avoid this problem?

**Comment by edcarroll** [comment]
@FezVrasta so I've had a play with the code and what's happened is the type definitions included with `popper.js` are actually different to the ones in `@types/popper.js`. Normally when a module includes its own defs the old @types ones are ignored, however in this instance they conflicted, causing the errors to appear.

As far as I can tell the types now included in `popper.js` will have broken all builds requiring the old types, because the original ones allows you to write:

```typescript
import Popper from "popper.js";

const myPopper = new Popper(...);

const modifiers:Popper.Modifiers = ...;
```

Whereas the guy that modified them in [the Popper.JS PR](https://github.com/FezVrasta/popper.js/pull/351) has made it so you need to write:

```typescript
import * as Popper from "popper.js";

const myPopper = new Popper.default(...);

const modifiers:Popper.Modifiers = ...;
```

Or (what I've done):

```typescript
import Popper from "popper.js";
import * as PopperTypes from "popper.js";

const myPopper = new Popper(...);

const modifiers:PopperTypes.Modifiers = ...;
```

This is a step backwards, and I would recommend a new release that includes the old type definitions.

**Comment by edcarroll** [comment]
@FezVrasta it wouldn't let me tag you in my previous comment, not sure why. Here is the tag anyway

**Comment by FezVrasta** [comment]
ping @giladgray, may you work on this?

**Comment by edcarroll** [comment]
@FezVrasta I'm happy to sort this out in a PR, as there are also a couple of other things missing in the type definitions that I'd like to fix 😄

**Comment by edcarroll** [comment]
@FezVrasta have just opened [a PR](https://github.com/FezVrasta/popper.js/pull/367) that fixes the issues I've mentioned above.

**Comment by edcarroll** [comment]
`0.9.4` is now live which locks down the Popper dependencies for now. @mvcoding this will sort out your build.

**Comment by mvcoding** [comment]
Great, thanks for the quick fix!

**Comment by earbullet** [comment]
This seems to have popped back up.  popper v1.14.1 came out just a few days ago.  I've explicitly set it to use the older version to workaround for now: "popper.js": "1.12.9"

ERROR in ../node_modules/ng2-semantic-ui/dist/modules/sidebar/services/sidebar.service.d.ts(13,11): error TS2503: Cannot find namespace 'Popper'.
../node_modules/ng2-semantic-ui/dist/modules/sidebar/services/sidebar.service.d.ts(14,12): error TS2503: Cannot find namespace 'Popper'.
../node_modules/ng2-semantic-ui/dist/modules/sidebar/services/sidebar.service.d.ts(15,10): error TS2503: Cannot find namespace 'Popper'.
../node_modules/ng2-semantic-ui/dist/modules/sidebar/services/sidebar.service.d.ts(16,13): error TS2503: Cannot find namespace 'Popper'.

**Comment by FezVrasta** [comment]
1.14.1 does export the namespace 🤔
