### ISSUE TITLE
Sidebar Output Event is emitting while the state never changed!

### ISSUE THREAD

**Issue by nikoszoisse** [edcarroll/ng2-semantic-ui#196]
### Bug description:
Hello, Seems that sidebar Module (isVisibleChange)="callback($event)" its fires when the initial state defined!

Isn't supposed to be fired only when really the state changed based on the initial state? 

### Version of Angular, ng2-semantic-ui, and Semantic UI:

Angular: latest

ng2-semantic-ui: latest

Semantic UI: latest

**Comment by edcarroll** [comment]
Could you please reproduce this in Plunkr? There are a couple of ways I can think this may be happening but can't be sure unless I see a repro. Thanks!

**Comment by nikoszoisse** [comment]
Here is a screenshot ngrx init store seems to pass the $event = Store
![image](https://user-images.githubusercontent.com/10202115/28669350-a8d48736-72dc-11e7-9aca-d77143d8bb72.png)

**Comment by edcarroll** [comment]
How are you binding `[isVisible]`? if you're using `ngrx` you should write `[isVisible]="isVisible | async"`.

Otherwise again I'll need a full reproduction to help.

**Comment by nikoszoisse** [comment]
You were right!!! Seems that isVisible got as value the Observable and not the value itself, the | async solved the problem, thank you and sorry for bother!

**Comment by edcarroll** [comment]
No worries! I've just started using `ngrx` myself in the last couple of weeks so run into this every now and again 😄 glad we got it sorted 🎉
