### ISSUE TITLE
Set locale globally?

### ISSUE THREAD

**Issue by mvcoding** [edcarroll/ng2-semantic-ui#197]
Just a little usage question about the new localization service. Do i have to set the locale separately in every component of my app that uses SUI components or is there a way to set it on global scope?

**Comment by edcarroll** [comment]
You can can set it globally by injecting the `SuiLocalizationService` and changing it there, which will update the language for the entire app 😄

**Comment by mvcoding** [comment]
Good to know, thanks! i will give it a try.
