### ISSUE TITLE
Angular 2 release candidate

### ISSUE THREAD

**Issue by mmazloum** [edcarroll/ng2-semantic-ui#2]
Hi again,
**
Upgrading to Angular 2 rc1 I get the follow errors when compiling : **
node_modules/ng2-semantic-ui/components/accordion/accordion-panel.component.ts(30,5): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<boolean>'.
  Type '{}' is not assignable to type 'boolean'.
node_modules/ng2-semantic-ui/components/checkbox/checkbox.component.ts(25,5): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<boolean>'.
  Type '{}' is not assignable to type 'boolean'.
node_modules/ng2-semantic-ui/components/dimmer/dimmer.component.ts(33,5): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<boolean>'.
  Type '{}' is not assignable to type 'boolean'.
node_modules/ng2-semantic-ui/components/dropdown/dropdown.service.ts(25,5): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<boolean>'.
  Type '{}' is not assignable to type 'boolean'.
node_modules/ng2-semantic-ui/components/dropdown/dropdown.service.ts(26,5): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<boolean>'.
  Type '{}' is not assignable to type 'boolean'.
node_modules/ng2-semantic-ui/components/message/message.component.ts(16,5): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<Message>'.
  Type '{}' is not assignable to type 'Message'.
    Property 'dismissible' is missing in type '{}'.
node_modules/ng2-semantic-ui/components/rating/rating.component.ts(32,5): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<number>'.
  Type '{}' is not assignable to type 'number'.
node_modules/ng2-semantic-ui/components/tab/tab.directive.ts(31,9): error TS2322: Type 'Observable<{}>' is not assignable to type 'Observable<Tab>'.
  Type '{}' is not assignable to type 'Tab'.
    Property 'id' is missing in type '{}'.
node_modules/ng2-semantic-ui/components/tab/tab.directive.ts(86,5): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<boolean>'.
  Type '{}' is not assignable to type 'boolean'.
node_modules/ng2-semantic-ui/components/tab/tab.directive.ts(87,5): error TS2322: Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<Tab>'.
  Type '{}' is not assignable to type 'Tab'.

**Besides I get this when I try to update / install packages : **

npm WARN ng2-semantic-ui@0.2.2 requires a peer of reflect-metadata@0.1.2 but none was installed.
npm WARN ng2-semantic-ui@0.2.2 requires a peer of rxjs@5.0.0-beta.2 but none was installed.

Do you plan to do an update ?

All the best.

**Comment by edcarroll** [comment]
Hey, will have a look into this tonight and release an update for tomorrow.

**Comment by edcarroll** [comment]
Hey, sorry for the delay on this - I have just released v0.2.3 which is a full upgrade to rc1, so your error should go away if you update. Please reopen this if you're still having issues!

**Comment by mmazloum** [comment]
great thanks a lot you were fast enough ;-) i'll keep you updated
