### ISSUE TITLE
SuiPopupModule not working at all

### ISSUE THREAD

**Issue by sunjoseph** [edcarroll/ng2-semantic-ui#204]
I'm integrating modal popup into my website, other modules work link charm, but this.
It doesn't pop template event hover like basic example below:
<button class="ui green icon button" suiPopup popupHeader="Example" popupText="This is an example popup">
    <i class="add icon"></i>
</button>
Hope you can help me.
Thanks in advantage.

**Comment by edcarroll** [comment]
Hi, please could you post a reproduction on Plunkr so I can investigate this further? Currently there isn't anything I can go on.

**Comment by namzee2013** [comment]
Seems this was conflicted with BrowserAnimationsModule module

**Comment by edcarroll** [comment]
@namzee2013  hmmm this has happened before. This must be to do with how the BrowserAnimationsModule controls the `transition` CSS property, as the library itself doesn't use this lib at all. Are you able to set up a plunkr so I can investigate a bit further please?

**Comment by namzee2013** [comment]
@edcarroll 
Please check this link https://plnkr.co/edit/eGsNmlbf9x1l83ZNzsLY?p=preview :)

**Comment by edcarroll** [comment]
@namzee2013 thank you for the plunkr 🎉 will take a look at this properly when I get some time.

**Comment by jmls** [comment]
ah - I think I just hit this as well ... any workarounds ?

**Comment by edcarroll** [comment]
This was a fun one! This was (somehow) due to the fact that the generated popup component was previously being detached and reattached on open - I've moved the detach to the destroy and close methods and things seem fine now.

Will put this fix out in the next release 😄

**Comment by edcarroll** [comment]
This is now live in `0.9.5`. Let me know if you have any further issues 😄

**Comment by preethis610** [comment]
SuiPopupModule not working at all

**Comment by edcarroll** [comment]
@preethis610 as above this is now fixed, upgrade to `0.9.5` 😄

**Comment by preethis610** [comment]
In 0.9.5 it is working...Thank you

**Comment by charlenebuena** [comment]
Updating ng2-semantic-ui to 0.9.5 also updates its dependency popper.js to the latest version that would later on produce error "Cannot find namespace 'Popper"

popper.js@1.14.1 didn't work for me
popper.js@1.12.9 worked for me

What I did:
`npm install ng2-semantic-ui@0.9.5 popper.js@1.12.9 --save`
