### ISSUE TITLE
sui-multi-select ngModel doesn't react on changes as it should

### ISSUE THREAD

**Issue by genuinefafa** [edcarroll/ng2-semantic-ui#206]
### Bug description:

When using `<sui-multi-select` if ngModel attribute is changed, nothing happend on component, hence, information might be out of sync.

### Link to minimally-working plunker that reproduces the issue:

Here is a [plunkr starter](http://plnkr.co/edit/CJaZ5J?p=preview) showing:
- a list that can be changed via a button, when it does change, nothing happen with selected options 
- if selected options are changed via a button (`.length = 0` for the array, as described [here](https://stackoverflow.com/a/1234337/1098814)) does not work (you can overwrite the array and *it does work*)

### Version of Angular, ng2-semantic-ui, and Semantic UI:

Angular: latest / current
ng2-semantic-ui: latest / current
Semantic UI: latest / current

**Comment by edcarroll** [comment]
Have made a PR that fixes this. Note that the 2nd one - `array.length = 0` still doesn't work, as Angular change detection isn't picking it up as a change - you'll need to open a bug report with them unfortunately.

**Comment by mcosta74** [comment]
According to the Angular Doc, to handle `options.lenght = 0` you should handle `DoCheck()`

**Comment by edcarroll** [comment]
This is now live in `0.9.5`. Let me know if you have any further issues 😄

**Comment by ashleyisles** [comment]
Dumb question, but I ran npm update but I'm still getting version 0.8.4. Do I have to reinstall it to update? @edcarroll

**Comment by edcarroll** [comment]
@ashleyisles this is because when a package version is `<1.0.0`, `^` matches only patch versions not minor versions. So you need to do `npm install ng2-semantic-ui@latest` 😄

**Comment by ashleyisles** [comment]
![image](https://user-images.githubusercontent.com/6678189/29436432-190a5f9a-8371-11e7-9c89-fd7e8c3e79c9.png)

Uh oh, what did I mess up?

**Comment by edcarroll** [comment]
Nothing, looks like npm is throwing a tantrum... easiest thing to do is just delete you node modules and run npm install again, should stop the error from happening.

**Comment by ashleyisles** [comment]
God bless you.

**Comment by edcarroll** [comment]
Glad it's sorted 😄

**Comment by zxxz** [comment]
The issue still occurs with version 0.9.6 and is reproducible as described here: http://plnkr.co/edit/BZL2xWreFYgIbNwSkLSL?p=preview

**Comment by edcarroll** [comment]
@zxxz please see my comments in the other issue 😄

**Comment by arron21** [comment]
@edcarroll does this update the class '.select' inside the <sui-multi-select> as well?
