### ISSUE TITLE
AOT build broken

### ISSUE THREAD

**Issue by slavik990** [edcarroll/ng2-semantic-ui#209]
We updated `ng2-semantic-ui` version  from `0.8.2` to `0.9.4`, and after that our AOT build fails:
```
    Error on fetch for ng2-semantic-ui/dist/modules/transition.js at /node_modules/ng2-semantic-ui/dist/modules/transition.js
	Loading ng2-semantic-ui/dist/modules/dimmer/dimmer.module.js
	Loading dist/tmp/web.module.ngfactory.js
	Loading dist/tmp/main.web.prod.js
	ENOENT: no such file or directory, open ng2-semantic-ui/dist/modules/transition.js'
Details:
    originalErr: Error: ENOENT: no such file or directory, open /node_modules/ng2-semantic-ui/dist/modules/transition.js'
Stack:
Error on fetch for ng2-semantic-ui/dist/modules/transition.js at node_modules/ng2-semantic-ui/dist/modules/transition.js
	Loading ng2-semantic-ui/dist/modules/dimmer/dimmer.module.js
	Loading dist/tmp/web.module.ngfactory.js
	Loading dist/tmp/main.web.prod.js
	Error: ENOENT: no such file or directory, open node_modules/ng2-semantic-ui/dist/modules/transition.js'
```
It seems problem with file import, when `index` omitted (like this https://github.com/angular/angular/issues/16152)
I manually added `index` to `transition` import path
`import { SuiTransitionModule } from "../transition";` => `import { SuiTransitionModule } from "../transition/index`
 it helps, but same problem present in import for other modules

**Comment by edcarroll** [comment]
Ah I see what's happening, the module loader is trying to bundle folders as if they're `js` files, correct?

What tool are you using to carry out the compilation? I'm testing at the moment with Angular CLI as well as `ngc` and not seeing this issue.

**Comment by slavik990** [comment]
Yes, correct.
We use `systemjs-builder`. Seems this not supported omit `index` in path - https://github.com/systemjs/systemjs/issues/1308

**Comment by edcarroll** [comment]
Hmm ok. when using other libraries do you encounter the same issues? To fix this does it just require changing the paths that rely on `index` automatically to actually specifying `index`?

**Comment by slavik990** [comment]
We use a lot of libraries and for it AOT build works well. And for `0.8.2` version of `ng2-semantic-ui` it also works.
Yes - just adding missing `index` in path fix this error.

**Comment by edcarroll** [comment]
Ok 2 things:

Firstly, I've made a PR that I think addresses this. Could you download the attachment, and copy the contents over your current `ng2-semantic-ui` in `node_modules` please? It should let you build now as all the `/index` things have been added (I hope).

Secondly, I've been wanting to move the library to use custom tsconfig paths rather than mega relative things. This will look like `import { Util } from "@sui/util";` or something along those lines. Typescript doesn't convert these paths when compiling, it just leaves them as is, so would this change be something that a) breaks your build system and b) something that you can map manually?

Once this is sorted it will go out in `0.9.5`.

[build.zip](https://github.com/edcarroll/ng2-semantic-ui/files/1216998/build.zip)

**Comment by slavik990** [comment]
1. Build works great, but something with modal vertical position(is it present for you? If no, I'll investigate it)
2. I checked but not find any information about supporting `tsconfig paths` for 'systemjs-builder', but if you want you can create simple build with few new `tsconfig paths` imports and I will check it.

**Comment by edcarroll** [comment]
1. Not seeing the issue myself, are you able to reproduce it in the test page? I can then try it out myself manually.
2. Not to worry - for now I'm going to leave as is and potentially will update things in `v0.10.0`. Will ping you if I do change it so you can test 😄

**Comment by edcarroll** [comment]
This is now live in `0.9.5`. Let me know if you have any further issues 😄

**Comment by bargoldi** [comment]
Hi @edcarroll ,
Looks like you really found the issue, but it seems like not everything got fixed yet.
e.g: sui.module.js tried to import from collections.js (needs to be collections/index.js). There are a few more of those.
