### ISSUE TITLE
How to center sui-pagination relative to its parent?

### ISSUE THREAD

**Issue by zxxz** [edcarroll/ng2-semantic-ui#211]
Hello,

How can I center a pagination component inside a segment (or relative to its parent)?

[http://plnkr.co/edit/EQdrGW2FV44AIgtXmHer?p=preview](url)

Thanks,
zxxz

**Comment by mcosta74** [comment]
you can use a `center aligned` segment

```
<div class="ui center aligned segment">
 ...
</div>
```

http://plnkr.co/edit/HNkelV?p=preview

BTW, for short question like "How to do ..." I'd suggest to use Gitter and not the Issues

**Comment by zxxz** [comment]
Thanks!

...and you are right, I should have asked it on Gitter, my bad 😔
