### ISSUE TITLE
Select and ChangeDetection

### ISSUE THREAD

**Issue by slavik990** [edcarroll/ng2-semantic-ui#213]
Select not shows options text on search when parent controller has ChangeDetectionStrategy.OnPush
Here plunker: http://plnkr.co/edit/BN6YuI50h0JlIZgb6HFu?p=preview

**Comment by slavik990** [comment]
Same problem even if it not direct parent - http://plnkr.co/edit/gdTLybf1TFCYLAIUSUfB?p=preview

**Comment by edcarroll** [comment]
This is now live in `0.9.5`. Let me know if you have any further issues 😄
