### ISSUE TITLE
Some demo page is broken when scrolling

### ISSUE THREAD

**Issue by ivivivn** [edcarroll/ng2-semantic-ui#22]
Hi @edcarroll 
![image](https://cloud.githubusercontent.com/assets/9279315/19107725/34a2309c-8b20-11e6-99e4-c007e0d3e8ea.png)

Please fixed the demo page. It went wrong when scrolling in some page liek http://edcarroll.github.io/ng2-semantic-ui/#/components/checkbox

Thanks

**Comment by 4tron** [comment]
The article section should not have a position:fixed; has the sidebar element is a child of the article . thats a quick fix

**Comment by edcarroll** [comment]
All sorted now. Thank you!
