### ISSUE TITLE
feature(Tabs) : tabs alignment feature

### ISSUE THREAD

**Issue by dev-fullstacktechnology** [edcarroll/ng2-semantic-ui#220]
I need feature for making tabs align on left, right and middle of space. May it is easy to make left, right and centered align tabs individually. Here is snapshot for requested feature.
![side_tabs](https://user-images.githubusercontent.com/22045550/29059222-2a4b831a-7c32-11e7-9d43-622a5d5d7390.png)
Let me know reviews of other peoples about his feature on messages.

Angular: ^4.2.2
ng2-semantic-ui: ^0.9.3
Semantic UI: 2.2.2

**Comment by edcarroll** [comment]
As per the other issue, this looks to be more of a CSS based task - and therefore out of the scope of this library. This library aims to not add any extra CSS functionality to the base Semantic UI library. Please open an issue over there to get this supported 😄
