### ISSUE TITLE
Other Directives

### ISSUE THREAD

**Issue by erslater** [edcarroll/ng2-semantic-ui#23]
Great work on this and it is much appreciated by all Angular developers!  

Do you have any plans on creating directives for other Semantic components and if so any timeline?

**Comment by edcarroll** [comment]
Hi there, I've just added a popup component to the list, so you can create tooltips and more advanced UI with it. I don't plan to add any more components until early summer due to external commitments, but will add an issue when I do. Thank you for your interest! 😄
