### ISSUE TITLE
AOT build broken - template variables

### ISSUE THREAD

**Issue by slavik990** [edcarroll/ng2-semantic-ui#247]
I checked `0.9.5` version. There present new problem with AOT build: 
```
dist/tmp/node_modules/ng2-semantic-ui/dist/modules/popup/components/popup.ngfactory.ts(233,43): error TS2339: Property 'template' does not exist on type 'PopupConfig'.
```
I investigated it and it seems problem with types of template variables(AOT compile templates and checks types for variable in all templates) at file popup.ts 
```  <ng-container *ngIf="!config.template && (!!config.header || !!config.text)">```

**Comment by edcarroll** [comment]
Ah good old AoT compilation. Will get a fix out for this in the next day or two.

**Comment by genuinefafa** [comment]
workaround by the time being `ng build --aot=false` (in any of the scripts, you might even use `ng build --prod --aot=false --sourcemaps`

**Comment by slavik990** [comment]
@edcarroll can you add checking AOT compilation on travis? If you want I can help you with it

**Comment by edcarroll** [comment]
@slavik990 that would be great if you could! At the moment it is compiled with `ngc`, but that doesn't always throw up the errors so I normally catch them with the demo app (though the demo app AoT doesn't actually compile due to the fact that the library code is outside of the demo app directory if you see what I mean?

**Comment by Drol** [comment]
`ERROR in ./node_modules/ng2-semantic-ui/dist/modules/select/components/select-option.ngfactory.ts
Module parse failed: C:\git\brandskyddsforeningen\hetaarbeten\Source\Cms\node_modules\ng2-semantic-ui\dist\modules\select\components\select-option.ngfactor
You may need an appropriate loader to handle this file type.
| import * as i0 from '@angular/core';
| import * as i1 from 'ng2-semantic-ui/dist/modules/select/components/select-option';
| const styles_SuiSelectOption:any[] = ([] as any[]);
| export const RenderType_SuiSelectOption:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
|     styles:styles_SuiSelectOption,data:{}});`

I get this error when using AoT

**Comment by genuinefafa** [comment]
@Drol can you provide non-working example? 
did you try refreshing `npm prune; npm install;` dependencies?

**Comment by Drol** [comment]
@genuinefafa It was a error I made in my webpack configuration. I had configure my typescript loader to ignore node_modules folder so it could not compile the genereated TS files in 'node_modules\ng2-semantic-ui\dist\modules'.

**Comment by edcarroll** [comment]
Right, fix for this is implemented in #259, which will go out tomorrow.

I've also _finally_ worked out how to add AoT support to the demo app, which in turn fully tests the library's AoT compatibility. This is now integrated into travis, so anything that breaks compilation will be caught by CI 🎉

**Comment by edcarroll** [comment]
...and we're live in `0.9.6` 🎉 The AoT checks in Travis are working nicely so let's hope we don't run into this again in the future!

**Comment by psychos4** [comment]
@Drol I have the same problem!
I have exclude the **node_modules** path, but no improvement. 

_tsconfig.json:_
`"exclude": [ "bin", "node_modules" ],`


>   ERROR in ./$$_gendir/~/ng2-semantic-ui/dist/modules/modal/components/modal.ngfactory.ts
    Module parse failed: C:\\Tests\Testprojekt\\$$_gendir\node_modules\ng2-semantic-ui\dist\modules\modal\components\modal.ngfactory.ts Unexpected token (16:21)
    You may need an appropriate loader to handle this file type.
    | import * as i5 from 'ng2-semantic-ui/dist/modules/transition/directives/transition';
    | import * as i6 from 'ng2-semantic-ui/dist/misc/util/services/component-factory.service';
    | const styles_SuiModal:any[] = ['.ui.dimmer[_ngcontent-%COMP%] {\n    overflow-y: auto;\n}\n\n\n.scroll[_ngcontent-%COMP%] {\n    position: absolute !important;\n    margin-top: 3.5rem !important;\n    margin-bottom: 3.5rem !important;\n    top: 0;\n}'];
    | export const RenderType_SuiModal:i0.RendererType2 = i0.ɵcrt({encapsulation:0,styles:styles_SuiModal,
    |     data:{}});
     @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts 10:0-116
     @ ./ClientApp/boot.server.ts

**Comment by Drol** [comment]
@psychos4 The problem I had was that node_modules was excluded. If I removed the exclude it worked.

**Comment by psychos4** [comment]
@Drol it takes no effect. maybe something else different in the tsconfig.json file?

> {
>   "compilerOptions": {
>     "module": "es2015",
>     "moduleResolution": "node",
>     "target": "es5",
>     "sourceMap": true,
>     "experimentalDecorators": true,
>     "emitDecoratorMetadata": true,
>     "skipDefaultLibCheck": true,
>     "skipLibCheck": true, // Workaround for https://github.com/angular/angular/issues/17863. Remove this if you upgrade to a fixed version of Angular.
>     "strict": true,
>    "strictNullChecks": false,
>     "noImplicitAny": false,
>     "lib": [ "es6", "dom" ],
>     "types": [ "webpack-env" ]
>   },
>   "exclude": [ "bin", "node_modules" ], // same error with "node_modules" and without  @Drol
>   "atom": { "rewriteTsconfig": false }
> }


>     ERROR in ./$$_gendir/~/ng2-semantic-ui/dist/modules/select/components/select-option.ngfactory.ts
>     Module parse failed: /Users/hannes/Documents/01 Projects/LiveAlarmierung/$$_gendir/node_modules/ng2-semantic-ui/dist/modules/select/components/select-option.ngfactory.ts Unexpected token (11:28)
>     You may need an appropriate loader to handle this file type.
>     | import * as i0 from '@angular/core';
>     | import * as i1 from 'ng2-semantic-ui/dist/modules/select/components/select-option';
>     | const styles_SuiSelectOption:any[] = ([] as any[]);
>     | export const RenderType_SuiSelectOption:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
>     |     styles:styles_SuiSelectOption,data:{}});
>      @ ./$$_gendir/ClientApp/app/components/prowl/list.component.ngfactory.ts 8:0-131
>      @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
>      @ ./ClientApp/boot.server.ts

**Comment by genuinefafa** [comment]
@psychos4 this appear to be different, AOT is a bunch of things, not any template error will be related with this AFAIK.

Why don't open a new issue so we can follow. :)
