### ISSUE TITLE
error: export declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by q986872053** [edcarroll/ng2-semantic-ui#25]
in app.module.ts i just write
...
import { SuiModule } from 'ng2-semantic-ui/ng2-semantic-ui';
...

@NgModule({
    imports:[...,
            SuiModule,
            ...],
    declarations: [ AppComponent],
    bootstrap:    [ AppComponent ]
})

...

and i hadn't use in other components,it cause 
error: export declarations may only appear at top level of a module,
when i remove 'SuiModule' from @NgModule({imports:[]}) it work well.
so what should i do.

**Comment by edcarroll** [comment]
This is now fixed in 0.5.0. Apologies for the delay!
