### ISSUE TITLE
select

### ISSUE THREAD

**Issue by yoonzm** [edcarroll/ng2-semantic-ui#254]
when select value is object, auto select is not work

**Comment by edcarroll** [comment]
Please could you add a reproduction in plunkr? The template is available when you create a new issue.

**Comment by jan831** [comment]
we have a similar issue, I'll try to a reproduction in plunkr later.   But I can explain it easily.

the value that is set via ngModel  is an object.   And that same object is not in the list of options.   In the option list, there is an item with the exact same keys & values.
It only matches if it is the exact same value as the one in the options list, even when using an optionsLookup

**Comment by jan831** [comment]
demo of the bug: http://plnkr.co/edit/VKEXH6fy1QWuq85U1ZpZ

I created a fork and fixed the issue:  https://github.com/jan831/ng2-semantic-ui
(first commit is the demonstration of the bug in the demo pages, second commit is the actual fix of the issue)

**Comment by edcarroll** [comment]
Thank you for both the repro & the fix! 🎉 Please could you open a PR linking the fork so I can pull in the changes?

**Comment by monothorn** [comment]
is this fix available on the latest version ?
