### ISSUE TITLE
Dropdown performance

### ISSUE THREAD

**Issue by slavik990** [edcarroll/ng2-semantic-ui#255]
We have a lot of dropdown on page, and same as in #194 we have problem with performance. It reproducible when input any text, http://plnkr.co/edit/n9kJ8cerRpX4yBFDinXQ?p=preview.
Seems it because `@HostListener("document:keydown", ["$event"])` at file https://github.com/edcarroll/ng2-semantic-ui/blob/master/src/modules/dropdown/directives/dropdown-menu.ts

**Comment by edcarroll** [comment]
This is now live in `0.9.6` 😄 I decided to turn all of the document `@HostListener`s into manual listeners to avoid this issue on other components in the future. Let me know if you still have any problems!
