### ISSUE TITLE
[Sui-multi-select] Options aren't bound to data

### ISSUE THREAD

**Issue by ashleyisles** [edcarroll/ng2-semantic-ui#257]
### Bug description:

I'm not sure if this is a bug or if it's by design, but I have a multiple select dropdown and an array called "environments", which is what I've set [options] to:
`<sui-multi-select  ... [(ngModel)]="selectedEnvironments" [options]="environments" #envSearch>`
(The ellipses represent other properties like class and placeholder and such).

The issue I'm having is that when this array "environments" is updated (And I've checked to make sure that it is), the options don't change. So for example if I have the options "dev", "prod" and "test", then I add a "nonprod" environment, I still only see the original 3.

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/48c52gfScIzWTPSj2sWm?p=preview

### Version of Angular, ng2-semantic-ui, and Semantic UI:

Angular: 4.3.5

ng2-semantic-ui: 0.9.5

Semantic UI: 2.2.13

**Comment by edcarroll** [comment]
Hi, thank you for opening the issue 😄 Having now looked into this properly, my initial assessment was wrong - since you're mutating the array, Angular change detection won't fire.

We don't intend to support manual dirty checking (as it's needlessly expensive), so to fix this do the following in your `add` function:

```typescript
add() {
    this.environments = [...this.environments, "pls"];
    console.log(this.environments);
}
```

This creates a brand new array which will fire the change detection round on the select component 😄

**Comment by ashleyisles** [comment]
Ahh, I gotcha. That makes sense!

Is this shorthand? I figure doing [this.environments, "pls"] would give me a nested array, no?

**Comment by ashleyisles** [comment]
Ahh, I gotcha. That makes sense!

Is this shorthand? I figure doing [this.environments, "pls"] would give me a nested array, no?

**Comment by edcarroll** [comment]
No worries! Was just writing to notice the use of the spread operator 😄 no problem!

**Comment by thomleonard** [comment]
Doing the change suggested in the Plunker doesn't actually fix it... am I missing something?
