### ISSUE TITLE
update usage doc to work with angular tutorial app

### ISSUE THREAD

**Issue by danyi-david** [edcarroll/ng2-semantic-ui#26]
Hi,

could you please update the documentation so that the module works with the step-by-step tutorial app on the angular2 site?

I've done the part mentioned:

``` javascript
import {SuiModule} from 'ng2-semantic-ui/ng2-semantic-ui';

@NgModule({
    declarations: [AppComponent, ...],
    imports: [SuiModule, ...],  
    bootstrap: [AppComponent]
})
export class AppModule {}
```

at this point the app will throw errors:

> /ng2-semantic-ui/ng2-semantic-ui 404 (Not Found)

figured I'd need systemjs.config.js to have something like this:

``` javascript
(function (global) {
  System.config({
...
    map: {
...
      'ng2-semantic-ui': 'npm:ng2-semantic-ui'
    },
    packages: {
...
      'ng2-semantic-ui': {
        defaultExtension: 'js'
      }
...
```

but now the app tries to load '/traceur' from the server, which it can't find.

> /traceur 404 (Not Found)

By looking at the sources I can't seem to find anything in the module code that would want to do that, but I'm lost at this point. All I could find was that this seems to be some transpiler. Is it a required dependency that I should also install and configure? Could you give me some pointers on how to do that?

thanks,
David

**Comment by JhookC** [comment]
Hi David, did you solve the problem? I have the same problem now.

**Comment by danyi-david** [comment]
I couldn't solve the problem sadly, so as ugly as it is I've switched to calling jQuery().dropdown() in ngAfterViewInit().
At least that works.

**Comment by edcarroll** [comment]
Hi there, apologies for not getting back to you sooner. I haven't worked with SystemJS myself - though this error seems to be to do with the usage of `ng2-semantic-ui/ng2-semantic-ui` - try with 0.5.0 and just `ng2-semantic-ui`. I'm going to close for now though, please reopen if this issue persists.
