### ISSUE TITLE
Query (Modal) : TS2346 : Supplied parameters do not match any signature of call target

### ISSUE THREAD

**Issue by dev-fullstacktechnology** [edcarroll/ng2-semantic-ui#268]
I have many of modals defined in my application. All modals are working correctly but my code quality tool TS Lint shows me an error as TS2346: Supplied parameters do not match any signature of call target. I don't know as it actually the problem with our library or in my settings of the development platform. I am using the latest version of WebStorm 2017.
![tslint_error](https://user-images.githubusercontent.com/22045550/29615239-bd3f7de4-882a-11e7-8603-04548a57e18a.png)

Anyone can check and let me know the correct solution.

### Version of Angular, ng2-semantic-ui, and Semantic UI:
Angular: ^4.2.2
ng2-semantic-ui: ^0.9.5
Semantic UI: 2.2.2

**Comment by edcarroll** [comment]
Please could you supply me with some more code so I can see what is going on more clearly? Thanks!

**Comment by dev-fullstacktechnology** [comment]
Here is my modal related code :

**Comment by aqmebrak** [comment]
I ran into this exact same problem: I created a clean angular-cli project, added the modal template example from the doc, and got the same error on the same line. The workaround @dev-fullstacktechnology provided in #290 seems to do the job.
