### ISSUE TITLE
A bug in a Dropdown component

### ISSUE THREAD

**Issue by loudandwicked** [edcarroll/ng2-semantic-ui#27]
Let's use code from Semantic-UI documentation to demonstrate this:

``` html
<div class="ui menu">
  <a class="item">
    Home
  </a>
  <div class="ui pointing dropdown link item" suiDropdown>
    <span class="text">Shopping</span>
    <i class="dropdown icon"></i>
    <div class="menu" suiDropdownMenu>
      <div class="header">Categories</div>
      <div class="item" suiDropdown>
        <i class="dropdown icon"></i>
        <span class="text">Clothing</span>
        <div class="menu" suiDropdownMenu>
          <div class="header">Mens</div>
          <div class="item">Shirts</div>
          <div class="item">Pants</div>
          <div class="item">Jeans</div>
          <div class="item">Shoes</div>
          <div class="divider"></div>
          <div class="header">Womens</div>
          <div class="item">Dresses</div>
          <div class="item">Shoes</div>
          <div class="item">Bags</div>
        </div>
      </div>
      <div class="item">Home Goods</div>
      <div class="item">Bedroom</div>
      <div class="divider"></div>
      <div class="header">Order</div>
      <div class="item">Status</div>
      <div class="item">Cancellations</div>
    </div>
  </div>
  <a class="item">
    Forums
  </a>
  <a class="item">
    Contact Us
  </a>
</div>
```

The problem here is that when you click on a `<span class="text">Clothing</span>` element in a nested dropdown, a dropdown gets closed as the component only checks if event.target has suiDropdown attribute, which in this example <span> of course does not have. It's the same problem when clicking on a divider or a header. A quick and dirty solution would probably be to just add a test for text|divider|header to check for in a class attribute, the same as you did for input|textarea. Do you think this is okay?

**Comment by edcarroll** [comment]
I've rewritten how the dropdown component works in 0.5.0, and this issue should be fixed - let me know if you still have any issues!

**Comment by loudandwicked** [comment]
The problem I was describing is gone now, thank you, but with this fix you introduced the opposite one.

```
<div class="ui menu large fixed inverted">
  <div class="menu">
    <div suiDropdown class="ui dropdown borderless item">
      <span class="text">Example</span>
      <i class="dropdown icon"></i>
      <div class="menu" suiDropdownMenu>
        <a class="item">
          <i class="home icon"></i>
          <span class="text">Sub 1</span>
        </a>
        <a class="item">
          <i class="home icon"></i>
          <span class="text">Sub 2</span>
        </a>
      </div>
    </div>
  </div>
</div>
```

Clicking on a <i class="home icon"></i> or on a <span class="text"> inside an item does not close the dropdown.

**Comment by edcarroll** [comment]
I see what's happened! Run `npm update ng2-semantic-ui` to get the latest version - I've included a fix for this. It now supports closing only when it is an item, or a child of an item that isn't an `input` or `textarea`. This also includes your PR regarding using target instead of srcElement.

**Comment by loudandwicked** [comment]
Yes, this is now working correctly, thank you :)
