### ISSUE TITLE
Text and value for select element

### ISSUE THREAD

**Issue by claudiu909** [edcarroll/ng2-semantic-ui#271]
Hi, How can I add id as value and name as test for select element? In the documentation I can see only [value] that is displaying the text for each option in the dropdown.

Thanks.

**Comment by Gimly** [comment]
Funny, I'm fighting with that exact same thing right now.

The only solution I have found is to bind the `options` property of the `sui-select`.  Then you do the *ngFor on the filteredOptions, and configure a `labelField` on the `sui-select`.

Probably clearer with code:

```Html
<sui-select class="selection"
                   placeholder="Icon"
                   labelField="key"
                   [options]="icons"
                   #iconsSelect>
    <sui-select-option *ngFor="let icon of iconsSelect.filteredOptions" [value]="icon"></sui-select-option>
    </sui-select>
```

The annoying thing is that the `[value]` has to be the object for it to work, so if you want to bind a property of the object (like an id) you'll have issues.

**Comment by claudiu909** [comment]
I used this: 
`<sui-select [(ngModel)]="language_id"
						labelField="name"
						valueField="id"
						#select>
				<sui-select-option *ngFor="let language of languages" [value]="language"></sui-select-option>
			</sui-select>`
Basically, language is an object containing "name" and "id".

Now my wondering is if I can use html for label?

**Comment by Gimly** [comment]
Thanks, hadn't seen the `valueField`, very useful.
