### ISSUE TITLE
typescript codigo en documentación 

### ISSUE THREAD

**Issue by antj95** [edcarroll/ng2-semantic-ui#272]
donde puedo encontrar las lineas de codigo typescript en la documentacion para implementarlo en mi proyecto.

**Comment by edcarroll** [comment]
What specifically would you like Typescript examples for? 😄 (@genuinefafa please could you lend a hand here?)

**Comment by genuinefafa** [comment]
¿Qué exactamente es lo que necesitás? @ZWTOKIO 

La idea es la misma para cualquier plugin de angular. Si necesitás alguna página en particular en español, la hacemos. Sólo decime cuál. .

**Comment by ZWTOKIO** [comment]
@genuinefafa  gracias por escribir, estoy probando el repositorio saludos.
