### ISSUE TITLE
integration of select component with a form

### ISSUE THREAD

**Issue by sinsunsan** [edcarroll/ng2-semantic-ui#276]
In your doc you do not mention form intergration. 

I checked the code and did not see any form control 
FormControl

Do you know if sui-select is usable as a form element in angular ? 

https://edcarroll.github.io/ng2-semantic-ui/#/modules/select

**Comment by edcarroll** [comment]
The select component is fully compatible with both template driven and reactive forms 😄

**Comment by edcarroll** [comment]
As are any of the other components with `ngModel` bindings FYI

**Comment by sinsunsan** [comment]
so we need to put [(ngModel)]="myselect" where myselect if the form control name?
And it will be integrated in the form ?

**Comment by sinsunsan** [comment]
would be nice to have an example inside a form in your code examples...

**Comment by sinsunsan** [comment]
I experimented, so the response is more when integrating with a form with just do not use [(ngModel)] but normal [control]="user.controls.name"
and it will work. 

I recommend reading https://coryrylan.com/blog/angular-custom-form-controls-with-reactive-forms-and-ngmodel
and testing with that code
https://embed.plnkr.co/Yj93mh5ZnX6ONtaMQPAQ/
