### ISSUE TITLE
Importants directives

### ISSUE THREAD

**Issue by clust3rsekt0r** [edcarroll/ng2-semantic-ui#28]
I love your project clean and simple, but one thing that for me is very important to have in the directive packages and are these items.

1 Grid element to resize by device and postitioning
2 Tables
3 Side Bars and menus.

**Comment by csepmdat** [comment]
@clust3rsekt0r 
Hi,
For me, I am using this https://akveo.github.io/ng2-smart-table/ for table. It works pretty good and simple as well.

**Comment by edcarroll** [comment]
Hi there - so the first two things you've mentioned are outside of the scope of this project; they can be implemented purely with CSS classes (see the SUI docs) and I don't want to litter the project with empty wrappers that just add a few classes - especially if the classes change, it just adds more work to stay up to date. Regarding the last item, sidebars - they're on the todo list, but I can't promise anything too soon. Will close for now, and reopen when I get started on this component.
