### ISSUE TITLE
Range / Slider request

### ISSUE THREAD

**Issue by devlfm** [edcarroll/ng2-semantic-ui#280]
Hi,

I really need a component for range, but semantic only have implementations with jquery.. It is possible to kindly add something similar to this: https://github.com/tyleryasaka/semantic-ui-range

Kind regards,
Rui

**Comment by edcarroll** [comment]
Hi Rui,

This is something that is being worked on currently, and there is an active PR for it (#173), so you can track progress there 😄

**Comment by devlfm** [comment]
Oh nice! Can't wait to try it! in the meanwhile I had to use something.. and end up choosing [nouislider](https://github.com/tb/ng2-nouislider) but I prefer not having many external modules+css, so, as soon as this is ready and merged, I'll test it right away!

Thank you,
Rui
