### ISSUE TITLE
sui-multi-select: unable to pre-select options

### ISSUE THREAD

**Issue by zxxz** [edcarroll/ng2-semantic-ui#282]
### Bug description:
When sui-multi-select is initiated with a non empty selection, no selection is rendered, hence the model and the view are not in sync.
 
### Link to minimally-working plunker that reproduces the issue:
http://plnkr.co/edit/BZL2xWreFYgIbNwSkLSL?p=preview

Linked to: https://github.com/edcarroll/ng2-semantic-ui/issues/206

### Version of Angular, ng2-semantic-ui, and Semantic UI:

Angular:

ng2-semantic-ui: **0.9.5, 0.9.6**

Semantic UI:

**Comment by jan831** [comment]
that looks related to https://github.com/edcarroll/ng2-semantic-ui/issues/254
I created a pull request that fixes a similar issue for single-select.  I didn't test it with multi-select but I assume it will fix this issue as well.

**Comment by zxxz** [comment]
@jmls on gitter provided a workaround:

> I have multi-select working with this http://plnkr.co/edit/YxNRijRk9S5RAQApwOGJ?p=preview
> the only thing is it turns selected into an array of id's , not objects. But it works 
> ( I added valueField = "id")

**Comment by edcarroll** [comment]
Hi, I'm sorry it's taken me so long to get to this. I'm afraid to say this isn't actually a bug, and is more a direct result of how Javascript object equality works. In the example, you use an array literal for the options, then set the selected options to a separate array literal. Despite the fact that the objects have the same structure, they are not the same object. (since `{} === {}` is false).

Your options from here are to either use `valueField` as mentioned before, or to set things up as follows:

```typescript
export interface IOption {
   property:string;
}

@Component({ ... })
export class MyComponent {
   public options:IOption[] = [{ property: "hello!" }, { property: "world!" }];
   public selectedOptions:IOption[] = [this.options[0]];
}
```

Doing this means that the objects pass the `===` equality test.

I hope that helps clear up this issue!

**Comment by jan831** [comment]
when working with a more complex model, it produces a lot unnecessary code if we would have to look up the selectedOptions from the options list each time.  The itemLookup is the perfect tool to have a more advanced "equality" check for the values.

this is a simplified example of what we have in our application, where we need to update the 2 fields with one of the possible values for SubDto

```typescript
SomeDto {
	id:number;
	subDto1:SubDto;
	subDto2:SubDto;
}

SubDto {
	id:number;
	name:String;
}

getSomeDtoById(id:number):SomeDto
getSubDtoList():SubDto[]
```

**Comment by edcarroll** [comment]
That's fair, I suppose I was only looking at the small plunkr example. Using options lookup is definitely a good way of doing this - and I now see exactly why you added the example in your PR 😄

**Comment by StefanKern** [comment]
How can you preselect / change the selection when using `[optionsLookup]`? The example references to the list of options but when using `[optionsLookup]` you don't have this list (loaded from the server, etc.)?

**Comment by AlexSmirnov9107** [comment]
I've found out the bug with comparing options. You can fix it by editing already complied file node_modules/ng2-semantic-ui/dist/modules/select/classes/select-base.js 
change this
` return options.find(function (o) { return value === _this.valueGetter(o) });`
to this
` return options.find(function (o) { return JSON.stringify(value) === JSON.stringify(_this.valueGetter(o)) });`

**Comment by AlexSmirnov9107** [comment]
or you can edit it in Src in the same file
