### ISSUE TITLE
bug(select): Slow performance with multiple selects

### ISSUE THREAD

**Issue by trevordaniels** [edcarroll/ng2-semantic-ui#284]
Many sui-selects (20-30+) on a page causes noticeable delay on user actions eg. typing text

Only happens in default change detection, no delay for push change detection.

http://plnkr.co/edit/BPg7e32EhduVlBCjS0eY

**Comment by Drol** [comment]
I have a similar problem. Actually it is not that many select components. Only 3-4 on one page. But some of them have many options in them, some almost 100.

Any ETA?

**Comment by thariel** [comment]
Any news on this? Got the same problem with the suiDropdown elements.

**Comment by YoYo35** [comment]
+1

**Comment by vietphu** [comment]
+1

**Comment by gabrieldoty** [comment]
+1

**Comment by vlados** [comment]
Any idea why this is happening?

**Comment by tibinthomas** [comment]
Change detection strategies made in project is making the problems.

**Comment by kjn2** [comment]
As indicated earlier, great library, but limited to small apps, be very careful using it for commercial products.

When is it going to be fixed ?

**Comment by edcarroll** [comment]
The fix for this will be live in 0.10.0, which you can use now with `ng2-semantic-ui@next` tag on npm. This includes full support for Angular 6. Let me know if you have any issues.

**Comment by gabrieldoty** [comment]
Still a couple bugs with the dropdown - I can make a PR, file a ticket, or
just let you know what I find - which do you prefer?

~Gabe

**Comment by edcarroll** [comment]
A PR would be awesome if possible please, thank you for your help with this!

**Comment by rhyre** [comment]
I've got problem with this as well but not as a performance hit but as a not showing dropdown. When clicking on dropdown before it has loaded all the options I think it hangs. And there is no way to show dropdown. As a fun fact when typing in input dropdown magically shows. But when I'm using select dropdown without input. I'm doomed

**Comment by edcarroll** [comment]
Hey @rhyre, do you think you can set up a repro so I can take a closer look at this please?

**Comment by rhyre** [comment]
I'd like to, but I'm busy with the project and have to dump the idea of using semantic ui because of this. 
I think it can be easy repro by using select with a lot of data to be loaded. And click on it like crazy person before it has rendered. Usualy 1 click was enough. Tried with latest alpha3 version on that time and still it was an issue.

**Comment by edcarroll** [comment]
No problem at all, thank you for the info!

**Comment by gabrieldoty** [comment]
@edcarroll do you know when you can pull in the fix for keyboard navigation to alpha?

**Comment by edcarroll** [comment]
@gabrieldoty sorry for the delay, have now published a new alpha with the `@next` tag. Let me know how you get on with it!

**Comment by edcarroll** [comment]
I see the problem, I made a mistake while pushing out the alpha. Try pulling the `next` tag again.

**Comment by gabrieldoty** [comment]
@edcarroll much better, thank you!!

**Comment by icruces** [comment]
Any news when this fix is going to be released? I have tried using `@next` but I get the following error: 

`import { SuiComponentFactory } from "ng2-semantic-ui/dist";`
`ERROR in src/app/core/modal.service.ts(3,50): error TS2307: Cannot find module 'ng2-semantic-ui/dist'.`

I need `ActiveModal` and `SuiComponentFactory` as I am extending `SuiModalService` in my project.

**Comment by afrancoc2000** [comment]
Hi, I tried version 0.10.0 but I'm still having the performance problem, I have a lot of options, more than 100 and I have to count to 10 to get the options to show up/refresh when selected/ hide de selectable options on click outside. Also when I get a second row of options selected the options to select don't move down hiding the selected options.

Have you tought of adding like a max options to show option? maybe that way the component wont get so slow, but I think you shouldn't close this issue yet.

Thanks

**Comment by afrancoc2000** [comment]
ok the shadowing of the options is my css problem :P but a property with max elements to show is still a good idea :)

**Comment by afrancoc2000** [comment]
So this is my idea to improve performance: use the optionsLookup property with this function:

    public filterCategoryOptions = (query: string) => {
      return new Promise<CategoryModel[]>((resolve, reject) => {
        const filtered = this.selectableCategories.filter(option => option.name.startsWith(query));
        if (filtered.length < 20) {
          resolve(filtered);
        }
        else {
          resolve(filtered.slice(0, 20));
        }
      });
    }

Hope it helps :) still testing though

**Comment by afrancoc2000** [comment]
Final version:

    public filterCategoryOptions = (query: string) => {
      return new Promise<CategoryModel[]>((resolve, reject) => {
        const filtered = this.selectableCategories.filter(option => option.name.toLowerCase().startsWith(query.toLowerCase()));
        if (filtered.length < 20) {
          resolve(filtered);
        }
        else {
          resolve(filtered.slice(0, 20));
        }
      });
    }
