### ISSUE TITLE
Text `null` in  Select component options in Microsoft Edge & IE11

### ISSUE THREAD

**Issue by slavik990** [edcarroll/ng2-semantic-ui#285]
It's only for Select component with template. Here a screenshot:
<img width="1680" alt="2017-08-31 15 25 20" src="https://user-images.githubusercontent.com/3853482/29923328-d901d526-8e61-11e7-8344-3d0a4ccf6676.png">

**Comment by yavorskiy-web** [comment]
Issue #278

**Comment by edcarroll** [comment]
Closing in favor of #278
