### ISSUE TITLE
Page sidebar with body context

### ISSUE THREAD

**Issue by icruces** [edcarroll/ng2-semantic-ui#288]
Hi,

I am trying to configure a page sidebar. Using native **Semantic-UI** I can just create the sidebar without any custom context (that is, using body context).

But I cannot figure it out how to do it with **ng2-semantic-ui**:

http://plnkr.co/edit/CIt3PTemScOvVZe0SuaA?p=preview

As you can see the animation doesn't work correctly. I have read the docs but it always uses a segment as context.

Thanks.

**Comment by harogaston** [comment]
If you just add `style="background:white"` to your `sui-sidebar-container` it will work properly.
For a full page sidebar, the only way so far is to place all of your page content within a `sui-sidebar-container`.

I'm not saying this behavior cannot be changed/improved. We could look into that.

**Comment by icruces** [comment]
@harogaston Thanks! It works with `style="background:white"`
