### ISSUE TITLE
Creating TemplateModalConfig causes error only when scripts are minified

### ISSUE THREAD

**Issue by szpetny** [edcarroll/ng2-semantic-ui#290]
### Bug description:

Using ng2-semantic-ui modal window I encountered a problem. After a project is build for production and scripts minified, when try to open a modal window get an error:

ERROR TypeError: Ul.b is not a constructor

 which is caused by this line of code:

`let config: any = new TemplateModalConfig(this.modalTemplate);`

In dev environment it works fine. Has anyone got a similar issue?

### Version of Angular, ng2-semantic-ui, and Semantic UI:

Angular: 4.3.5

ng2-semantic-ui: 0.9.6

Semantic UI: 2.2.12

**Comment by dev-fullstacktechnology** [comment]
I will rather than going with conventional syntax they provide and it works fine for me.
Here is syntax and let me know if it works for you or not.
this.amazonWizardModal = new TemplateModalConfig<string, string, string>(this.amazonModal);

**Comment by szpetny** [comment]
Hi, thanks apparently it helped :)
