### ISSUE TITLE
sui-rating don't bind ngModel

### ISSUE THREAD

**Issue by Bill-Niz** [edcarroll/ng2-semantic-ui#293]
Hi,
I've got :
Template parse errors:
Can't bind to 'ngModel' since it isn't a known property of 'sui-rating'.

**Comment by icharge** [comment]
![image](https://user-images.githubusercontent.com/1619007/37878173-d5116b82-308e-11e8-8298-30561484583b.png)
This is not working at all. Tried on `[value]` or `[ngModel]`.

**Comment by edcarroll** [comment]
Do you definitely have `@angular/forms` imported? Otherwise, could you get this error to occur in a plunkr so I can take a look please?

**Comment by icharge** [comment]
I don’t use a form. So I need to display only and I can’t use ’[value]’

**Comment by edcarroll** [comment]
Right I understand - will get that PR looked at soon and merged to sort this out 😁

**Comment by icharge** [comment]
Thank you
