### ISSUE TITLE
Question : semantic ui .modal('show')

### ISSUE THREAD

**Issue by mmazloum** [edcarroll/ng2-semantic-ui#3]
Hi,

Everything seems to work fine for now, do you now a simple way to display a semantic UI modal ? They use to implement a jquery .modal('show'), I'm still looking for a solution without JQuery.

Are you planning to add the modal semantic component ? Otherwise I'll figure it out on my own.

Thanks.

**Comment by mmazloum** [comment]
found something binding css classes from semantic UI modals on component property. If you want a code extract  (I guess you don't ;-)) tell me.

all the best.

**Comment by edcarroll** [comment]
Hey, I am interested in implementing the modal component at some point, though I wanted to get the select fully finished and a popover component in first. Do show me your code extract though, always appreciate help getting off the ground!! :)

**Comment by mmazloum** [comment]
my modal is hidden in the dom at first, and in the host component html (retour-mod is the modal directive and it is surrounded by a div with quite similar css properties), i do somthing like: 

`
<div [ngClass]="{
        'ui': true, 'dimmer': true, 'modals': true, 'page': true, 'transition': true,
        'hidden': !isModalActive, 'visible': isModalActive, 'active': isModalActive}"
     [ngStyle]="{display: isModalActive ? 'block' : 'none'}"
     (click)="closeModal()">
  <retour-mod (closeModal)="closeModal()"></retour-mod>
`

And In the modal component ("isOn" is a boolean property of my modal component) : 
`
<div id="RetourModal"
    [ngClass]="{
       'ui': true,
       'small': true,
       'modal': true,
       'transition': true,
       'visible': isOn,
       'active': isOn,
       'hidden': !isOn,
       'dimmer': !isOn}"
    [ngStyle]="{
       marginTop: isOn ? '-275.5px' : '0px' ,
       display: isOn ? 'block' : 'none'}" (click)="OnClick($event)">
`

This is just a beginner code, and I don't like using ngStyle and ng class at the same time, but since it seems to work... And I loose the transition effect the original semantic UI modal has when it appears.

**Comment by mmazloum** [comment]
And +1 for the select component I need it too ;-)

**Comment by edcarroll** [comment]
I am still as of yet undecided how to implement the modals, so will close this for now. Sorry for the huge delay!!

**Comment by henninga** [comment]
+1 for modal
