### ISSUE TITLE
Passing undefined object to <sui-select> throws an error

### ISSUE THREAD

**Issue by GregOnNet** [edcarroll/ng2-semantic-ui#30]
Hey there,

I recognized the following error-message binding `undefined` to `[options]` to `sui-select`:

![image](https://cloud.githubusercontent.com/assets/444278/19644567/c1864c4e-99f0-11e6-8242-e8c3af7a2d3b.png)
## Why do I need `sui-select` to handle `undefined`

When options are loaded asynchronuously we have a state where `options` are undefined for a short amount of time.
## Where is the issue located

I think it is missed to check whether `options` is undefined: https://github.com/edcarroll/ng2-semantic-ui/blob/master/components/select/select.ts#L82

That's why an error is thrown.
## Benefit of the fix

If `<sui-select>` accepts `undefined` values the `async`-Pipe would work with this compoennt.

Can you have a look on this issue?

Thanks & Kinds
Greg

**Comment by edcarroll** [comment]
This is now sorted in 0.5.0. Apologies for the delay!
