### ISSUE TITLE
feat(select) labelField shouldn't be dependant on the value

### ISSUE THREAD

**Issue by Gimly** [edcarroll/ng2-semantic-ui#300]
I feel that the labelField being dependant from the select option's value parameter makes scenarios where we are binding to an id instead of the whole object unnecessarily complicated. Here's an example below that shows what I mean:

First, a working example using the standard select
```HTML
<select name="carType_{{i}}" [(ngModel)]="myCar.carTypeId" class="ui compact selection dropdown">
    <option *ngFor="let carType of carTypes" [ngValue]="carType.id">{{carType.name}}</option>
</select>
```
As you can see, I'm binding to the `catTypeId` because I dont' want to have the whole type object in the "parent" object (myCar). Then, I'm binding the value to the `CarType`'s `id` property and the display is coming from another property called `name`.

Now, the same example with `sui-select`. If I try to do this like that, it won't work because the `labelField` will try to get the property `name` from the `carType.id` which is just a `number`. This is really annoying and necessitate then a complex workaround (which I'm not really sure how to do elegantly).

```HTML
<sui-select class="compact selection dropdown" [(ngModel)]="myCar.carTypeId" 
            [options]="carTypes" labelField="name" name="carType_{{i}}" #select>
    <sui-select-option *ngFor="let option of select.filteredOptions" [value]="carType.id">
    </sui-select-option>
</sui-select>
```

I feel like that is a very common scenario which should be as simple as it is with the "standard" select.

I think that could be fixed by having the `labelField` on the `select-option` instead of the `sui-select`. This way, I could simply do something similar to this:
```HTML
<sui-select-option *ngFor="let option of select.filteredOptions" [label]="carType.name" 
                   [value]="carType.id">
</sui-select-option>
```

**Comment by edcarroll** [comment]
Apologies for the slow reply. Does `valueField` not suit your use case?

**Comment by Gimly** [comment]
Thanks a lot for your answer! Yes, the valueField suit my use case! I had completely missed it, it completely makes sense since we already have the labelField.

Thanks again for the help, closing the issue.

**Comment by edcarroll** [comment]
No problem, glad I could help 😃
