### ISSUE TITLE
Datepicker 

### ISSUE THREAD

**Issue by charlenebuena** [edcarroll/ng2-semantic-ui#303]
Why is the look of the datepicker like this?

![screen shot 2017-09-22 at 12 46 12 pm](https://user-images.githubusercontent.com/17472112/30729753-83dcfece-9f94-11e7-89a5-f41a76f37f68.png)

There is padding, the year is not located between the left and right buttons and the width is short. I didn't change anything. I just applied this code

```
<div class="content">
      <span class="title"> Invoice Deadline </span>
       <div class="sub header ">
               <div class="ui icon input">
                   <input suiDatepicker
                          id="deadlineOption"
                          [pickerMode]="'month'">
                   <i class="remove link icon" (click)="clearInput()"></i>
               </div>
       </div>
</div>
```

**Comment by edcarroll** [comment]
You're missing the CSS for the datepicker - follow the instructions [in the docs](https://edcarroll.github.io/ng2-semantic-ui/#/modules/datepicker) 😃
