### ISSUE TITLE
Multi select options not hidding on selecting and on searching

### ISSUE THREAD

**Issue by claudiu909** [edcarroll/ng2-semantic-ui#304]
### Bug description:

- on selecting multiple options the selected options are not hidding;
- searching the not matching options are still in the list;
- "No results" is appearing when all options are selected.

### Repo:

Please check this plunkr
http://plnkr.co/edit/P7T7wBMloOZ5q9LwU1CK?p=preview

### Versions:

Angular:
4.3.5
ng2-semantic-ui:
0.9.6
Semantic UI:
2.2.12

**Comment by edcarroll** [comment]
Hi there, I've had a look at your plunkr and this is happening because you're not making use of `filteredOptions`, explained in the [docs](https://edcarroll.github.io/ng2-semantic-ui/#/modules/select). This will sort out the hiding problem!
