### ISSUE TITLE
Displaying date format

### ISSUE THREAD

**Issue by claudiu909** [edcarroll/ng2-semantic-ui#308]
Can anyone help me how can I change the date format for displaying?

Also there is any way to change the format of how it is saved in the ngModel?

Sorry, but I didnt understand from documentation.

Thank you!

**Comment by trevordaniels** [comment]
You can add something like this to your root component to change it globally
```js
import { SuiLocalizationService } from 'ng2-semantic-ui';
import au from 'ng2-semantic-ui/locales/en-AU';

constructor(localizationService: SuiLocalizationService) {
  localizationService.load("au", au);
  localizationService.patch("au", {
    datepicker: {
      formats: {
	date: "DD/MM/YYYY"
      }
    }
  });
  localizationService.setLanguage("au");
}
```
afaik the datepicker always returns a date object. You could try implementing a setter method on the model property to see if you can intercept it, or listening to pickerSelectedDateChange.

**Comment by claudiu909** [comment]
Thanks. I'll try it.

**Comment by alexvingg** [comment]
When i define patch of localizationService in root component the format wont work but when in a feature component that will use the datepicker it works.


when i patch here datepicker in UserComponent still show en-GB language
`
export class AppComponent implements OnInit {

  constructor(
    public localizationService: SuiLocalizationService) {

    localizationService.load('pt', localizationPt);
    localizationService.patch('pt', {
      datepicker: {
        formats: {
            date: 'DD/MM/YYYY',
            datetime: 'DD/MM/YYYY'
        }
      }
    });
    localizationService.setLanguage('pt');
  }
`

when i patch  datepicker here direct in UserComponent show pt language but only in this component

Remember that i load UserComponent throuth lazy load UserModule .

`
export class UserComponent implements OnInit {

  constructor(
    public localizationService: SuiLocalizationService) {

    localizationService.load('pt', localizationPt);
    localizationService.patch('pt', {
      datepicker: {
        formats: {
            date: 'DD/MM/YYYY',
            datetime: 'DD/MM/YYYY'
        }
      }
    });
    localizationService.setLanguage('pt');
  }
`
