### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by simkepal** [edcarroll/ng2-semantic-ui#31]
How is it going with Modal. Will be awailable any time soon?

Thank you for you help!

Best regards...

**Comment by mmazloum** [comment]
If that can help, In my project my modals are components, and I set them to visible or not with the ngClass binding.

**Comment by mcelliott** [comment]
Having one modal and passing it a template similar to ng-bootstrap would be nice. https://ng-bootstrap.github.io/#/components/modal.

**Comment by edcarroll** [comment]
Hi there, I'm afraid the modal component is not high on the list of priorities. You can get something working using [suiTransition] and the right HTML & CSS - leverage the router for the transitions. Will reopen this when I get around to starting the modal component myself 😄

**Comment by edcarroll** [comment]
Just a status update - I'm now starting work on a modal component, and am tracking progress in #78. Follow there for news over the course of the next week.
