### ISSUE TITLE
sui-tabset with directives applied on nested elements in content or header

### ISSUE THREAD

**Issue by bogalex93** [edcarroll/ng2-semantic-ui#312]
sui-tabset is not working when having custom directives applied on nested elements in tab content or tab header. I receive the following error: 

SettingsLogsComponent.html:1 ERROR TypeError: Cannot set property 'isActive' of undefined
    at SuiTabset.set [as activeTab] (tabset.js:28)
    at SuiTabset.webpackJsonp.../../../../ng2-semantic-ui/dist/modules/tabs/components/tabset.js.SuiTabset.activateFirstTab (tabset.js:115)
    at SuiTabset.webpackJsonp.../../../../ng2-semantic-ui/dist/modules/tabs/components/tabset.js.SuiTabset.loadTabs (tabset.js:86)
    at SuiTabset.webpackJsonp.../../../../ng2-semantic-ui/dist/modules/tabs/components/tabset.js.SuiTabset.ngAfterContentInit (tabset.js:40)

**Comment by rhefner** [comment]
+1 I'm seeing the same thing, even without having custom directives like @bogalex93 .. Even a simple example throws the error above:

`<sui-tabset>
    <div class="ui top attached tabular menu">
        <a class="item" suiTabHeader="1">First</a>
        <a class="item" suiTabHeader="2">Second</a>
        <a class="item" suiTabHeader="3">Third</a>
    </div>
    <div class="ui bottom attached segment" suiTabContent="1">First tab!</div>
    <div class="ui bottom attached segment" suiTabContent="2">Second tab!</div>
    <div class="ui bottom attached segment" suiTabContent="3">Third tab!</div>
</sui-tabset>`

**Comment by rhefner** [comment]
Hmm, in the process of updating to Angular@5 and a few other things, this seems to be working for me now.

**Comment by zortx233** [comment]
@rhefner I am running into this issue using Angular 5.2... is there anything specific you did to fix this?
Could you list which typescript version you are using?

**Comment by zortx233** [comment]
Well, I figured out why I was getting this.. I had a div with the class of 'item' without a corresponding 'suiTabHeader' attribute. Once I removed that, I no longer get the error.

**Comment by rhefner** [comment]
@zortx233: Glad you got it figured out!  For future reference, I'm on latest angular/typescript.

**Comment by edcarroll** [comment]
Glad you've got that sorted also! Closing for now.

**Comment by luke-95** [comment]
Hello @edcarroll,

The current implementation causes the error mentioned by bogalex93@ when using tab menus of the form:
```
<sui-tabset>
    <div class="ui two item menu">
        <a class="active item" suiTabHeader="1">First</a>
        <a class="item" suiTabHeader="2">Second</a>
    </div>
    <div class="ui vertical segment" suiTabContent="1">First</div>
    <div class="ui vertical segment" suiTabContent="1">Second</div>
</sui-tabset>
```

Suspected reason:
The `ui two item menu` class contains the term `item`, which will trigger the code to look for a `suiTabHeader` attribute.
