### ISSUE TITLE
Angular Cli Build

### ISSUE THREAD

**Issue by simkepal** [edcarroll/ng2-semantic-ui#32]
Hello, 

I have a problem. I use Angular cli for my project. And when I try to make a final build I get this error.

Unexpected value 'SuiModule' imported by the module 'AppModule'
Angular cli command: ng build --prod --aot

Can you please help me with this?

Thank you!

**Comment by GregOnNet** [comment]
Hi @simkepal,

I am working on that issue.
When I have tested my setup (see https://github.com/GregOnNet/ng2-semantic-ui/tree/aot) I will prepare a pull request.

Kinds
Greg

**Comment by GregOnNet** [comment]
You can find my PR here: #42

**Comment by genuinefafa** [comment]
I'm currently getting a `ERROR in SuiModule is not an NgModule` with beta.32.3 version, is it the same problem?

Here the `ng -v` result
```
                             _                           _  _
  __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
@angular/cli: 1.0.0-beta.32.3
node: 7.0.0
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8
```

**Comment by genuinefafa** [comment]
I notice that you change *a lot*... Can you tell me what was causing that issue?

**Comment by GregOnNet** [comment]
Hi,

the issue was that ng2-semantic-ui was not prepared to be compiled in `AoT` mode.
I restructured the project to get the AoT-Build to work.

Hope this helps.
If you have any further questions please ask. :-)

Kinds
Greg

**Comment by genuinefafa** [comment]
So... If you don't support `AoT` your module will not be compatible? is that so?

ps: to be blunt, i'm not entirely sure why `AoT` is so important, but I'll learn eventually

**Comment by edcarroll** [comment]
It currently seems that way - the angular cli doesn't like including NgModules that weren't transpiled using `ngc`, which doesn't work unless you support AoT, hence the requirement.

AoT is useful because it gets rid of a loading step within your browser, which lowers the overall filesize of your program while also making it appear more quickly.
