### ISSUE TITLE
how to init select default value in ui select

### ISSUE THREAD

**Issue by sokhomhuy** [edcarroll/ng2-semantic-ui#329]
here is my code:
- ts
   lists = [
{ "name": "Default 1", "value": { "id": 1, "taxName": "Default 1", "taxRate": 16, "isActive": true } },
{ "name": "Default 2", "value": { "id": 2, "taxName": "Default 2", "taxRate": 10, "isActive": true } },
{ "name": "Default 3", "value": { "id": 3, "taxName": "Default 3", "taxRate": 15, "isActive": true } },
];
selectedDefault: = { "name": "Default 2", "value": { "id": 2, "taxName": "Default 2", "taxRate": 10, "isActive": true } };

- view 
<sui-select class="selection"  #select
                    [(ngModel)]="selectedDefault"
                    (ngModelChange)="selectedTaxChange.emit($event)"
                    [options]="lists"  style="width:100%"  labelField="name"
                    valueField="value"  [isSearchable]="searchable" [isDisabled]="disabled">
            <sui-select-option *ngFor="let option of select.filteredOptions" [value]="option">/sui-select-option>
        </sui-select>

**Comment by rhefner** [comment]
@sokhomhuy: In case you haven't figured it out yet, you're setting 'selectedDefault' to something that's not a value for the control. If you want to set a default value, you can set on component init like so: `this.selectedDefault = this.lists[1].value` or 1) use just the value portion of 'selectedDefault' or 2) setup your structure in a different way if you want to set 'selectedDefault' in it's definition.

**Comment by edcarroll** [comment]
As @sokhomhuy, the initial value has to be something in the list, as within a select equality checks are done referentially, rather than structurally.
