### ISSUE TITLE
How to create and open a popup in ngOnInit() ?

### ISSUE THREAD

**Issue by landru29** [edcarroll/ng2-semantic-ui#336]
How to create and open a popup when creating a view ?
I need to have the popup opened (depending on a value in the local storage)

I tried this: 
```
<div suiPopup popupText="yo" popupTrigger="manual" #tip="suiPopup">
```

```
@ViewChild('tip') tip: any;

ngOnInit () {
   this.tip.popup.open();
}
```

**Comment by vaso991** [comment]
ngAfterViewInit()

**Comment by edcarroll** [comment]
Looks like this is sorted, let me know if you still have any issues!
