### ISSUE TITLE
Selected element not marked as selected in <sui-select>

### ISSUE THREAD

**Issue by uNki23** [edcarroll/ng2-semantic-ui#34]
Hi there!

Possibly something to do with #33 

Expected behaviour: selecting an element marks the element as selected in the result list as seen in [http://semantic-ui.com/modules/dropdown.html#search-selection](http://semantic-ui.com/modules/dropdown.html#search-selection)

Thank you!

**Comment by edcarroll** [comment]
Hi there, this is now sorted in 0.5.0. Apologies for how long it has taken to get to this!
