### ISSUE TITLE
Performance issue with ng2-Semantic dropdown and Tooltip

### ISSUE THREAD

**Issue by preethis610** [edcarroll/ng2-semantic-ui#345]
I used the code sample from the documentation. It is working fine with a single dropdown/tooltip. When I use more number of Dropdowns in a component, it is affecting the entire project.Performance is poor and I couldn't able to type in the input fields of even other components, I am getting "[Violation] 'keydown' handler took 3141ms" in Verbose mode.Using more number of tooltips is showing [Violation] 'click' handler took 624ms, when I click anywhere in the project.Could anyone give me a solution.

**Comment by NikhilRadadiya** [comment]
@preethis610 Having same issue, seems like I have to change the component

**Comment by edcarroll** [comment]
Closing as duplicate of #284
