### ISSUE TITLE
This seems dead, no action in 4 months...that's years in internet age.

### ISSUE THREAD

**Issue by kjn2** [edcarroll/ng2-semantic-ui#346]
If anybody is offering commercialized support, please leave a pointer.   Currently, we are forced to do design workarounds to avoid existing bugs, affecting user experience.

**Comment by scblur869** [comment]
i have not seen any contributions from anyone myself on this. I really love this semantic ui implementation so I hope it stays alive and progresses!!

**Comment by kjn2** [comment]
fully agree, great implementation... no jQuery!...  we're basing a commercial product on this, which maybe is a mistake, because the bugs we find are in some basic components (e.g. drop-down listbox, tooltip).  So, if the authors have given up on that, then you can use this for prototyping and mini-apps only.

**Comment by scblur869** [comment]
might be worth you checking out Clarity Design System.. its a nice alternative .

**Comment by wolfrubin** [comment]
According to some earlier PRs raised. @edcarroll is travelling around the world at the moment and the project is on hold until he's back.

**Comment by stephenasamoah** [comment]
Thanks for that pointer, @scblur869 . It does look nice. I'm building a large commercial application and the bugs on this build are a huge blocker.

**Comment by d48** [comment]
@stephenasamoah what specific bugs that are blockers for your application? We are researching using it ourselves and we are trying to get some insight. Thanks!

**Comment by edcarroll** [comment]
I'm sorry for the lack of communication about the project. Things have been extremely busy over the last 6 months, and although things will remain busy I'm hoping to be able to start working through the backlog in the coming weeks.
