### ISSUE TITLE
No explicit open() method on SuiModal

### ISSUE THREAD

**Issue by petervelosy** [edcarroll/ng2-semantic-ui#347]
### Bug description:
A sui-modal is open by default, and transitions into a hidden state internally in such a way which is not straightforward to override. Once it has been closed, there is no method I can call on it that restores it to its initial state. This makes the <sui-modal> a single-use component, not suitable for repeatedly used modals (eg. a delete confirmation dialog that has to be opened up multiple times on the same page).

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/Tis5ylQl6yYEps5KEuEa?p=preview

### Version of Angular, ng2-semantic-ui, and Semantic UI:

Angular: 5.2.5

ng2-semantic-ui: 0.9.6

Semantic UI: 2.2.14

**Comment by avaneev95** [comment]
You're using basic automatic modal. It is designed to open only once as soon as the component is rendered. Consider using template or component based modals. These modals can be controlled by `SuiModalService`. Please, see the [documentation](https://edcarroll.github.io/ng2-semantic-ui/#/modules/modal).

**Comment by petervelosy** [comment]
Thank you very much.

In this case I would suggest an update in the documentation. I think Automatic, Template Based and Component Based are not the most appropriate headlines, as they refer to implementation details instead of semantic categories (i.e. what kind of a behaviour do I want to achieve?). A user of the library generally doesn't care first about whether he wants to put the modal into a separate component or not, but whether he wants it to be reopenable, or whether he wants it to be reusable elsewhere.

I would also change the order of the three headlines to reflect their probability of usage. The default behaviour one expects from a modal in any framework is definitely not Automatic, but any of the latter two. Hence, I would put those first.

**Comment by petervelosy** [comment]
Maybe the headline buttons in the documentation could contain both names, i.e. Automatic (Single use), Component Based (Reusable), etc.

**Comment by edcarroll** [comment]
Re documentation - looking to clarify modal documentation in #311, so will track things there. Looks like the main issue is sorted though.
