### ISSUE TITLE
How to use SuiTransition example without @ViewChild

### ISSUE THREAD

**Issue by kentoj** [edcarroll/ng2-semantic-ui#35]
For animating a transition from component code I have to use @ViewChild currently, which uses `ElementRef`. The [Angular Docs](https://angular.io/docs/js/latest/api/core/index/ElementRef-class.html) say that `ElementRef` is a security risk. Is there another way to use transition than using @ViewChild to get the element that needs to be transitioned?

Here is an example of how I have used it:

**home.component.ts**
```
import {Component, OnInit, ViewChild, Renderer} from '@angular/core';
import {SuiTransition} from "ng2-semantic-ui/components/transition/transition";

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  @ViewChild('banner') banner;

  myTransition: SuiTransition;

  constructor(private renderer: Renderer) { }

  ngOnInit() {
    this.myTransition = new SuiTransition(this.banner, this.renderer);
    this.myTransition.animate({name: "scale", duration: 1000});
  }

}
```

**home.component.html** partial
```
<div class="ui hidden information" suiTransition #banner>

</div>
```

**Comment by edcarroll** [comment]
Hi, apologies for the slow reply on this one. Version 0.5.0 includes a complete rewrite of how the SuiTransition component works, so you can just put `[suiTransition]` on the element you want to control. [See the docs for full instructions on how to do this](http://localhost:4200/#/components/transition).
