### ISSUE TITLE
api for opening messages

### ISSUE THREAD

**Issue by marshallcool** [edcarroll/ng2-semantic-ui#352]
Please read https://github.com/edcarroll/ng2-semantic-ui/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

How to create a common service for calls to the message component? I found api just to close it

Angular:

ng2-semantic-ui:

Semantic UI:

**Comment by edcarroll** [comment]
You can do what you're wanting to do with an array bound with an `*ngFor` - add things to the array for the message to appear, e.t.c.

There is a PR in progress looking at adding a lot more functionality to the message component - based on issue #103. This includes what you're looking for service wise, so closing this to track there.
