### ISSUE TITLE
Shape compatibility

### ISSUE THREAD

**Issue by kentoj** [edcarroll/ng2-semantic-ui#36]
Feature Request: Shape module
Semantic Documentation link: http://semantic-ui.com/modules/shape.html#shape
The shape module is really cool and would be a nice addition. Do you have any guides, other than the code, on how to bring a semantic component or module into this library? If you do then I would likely contribute a PR with the shape module implementation

**Comment by edcarroll** [comment]
Apologies for the delay getting back to you on this. The shape component is a tricky one, as it doesn't seem to leverage the Transition component, so can't be easily ported with existing code. In terms of bringing things across, I essentially try to mirror as much of the essential functionality as possible, but only at an interface level - none of the implementation details are taken from the original project.

If you're able to take a look at some of the current implementation of components, and suggest a way that the shape component could be done that fits with how the others are done, I'd be happy to work with you on that - but won't be able to add any more full components myself until at least July I'm afraid.
