### ISSUE TITLE
Close Modal from a different method instead modal.approve()

### ISSUE THREAD

**Issue by ParVisual** [edcarroll/ng2-semantic-ui#364]
Hi, I have a form inside my modal. 

I need to validate the form before closing the modal.

If I use the modal.approve() / onApprove() way, the modal closes automatically.

I need to "validateForm()"  and then, if  all is ok, closing the modal.

Is there a way to do that?

Thanks.

**Comment by edcarroll** [comment]
What about passing the modal reference as a parameter to the click function?

For example:

```html
<button (click)="submit(modal)">Submit</button>
```

```ts
function submit(modal):void {
    validateForm();
    modal.approve(...);
}
```

**Comment by ParVisual** [comment]
Hey, works fine, thank you!

**Comment by edcarroll** [comment]
No problem, glad you got it sorted!
