### ISSUE TITLE
Datepicker - changing date format

### ISSUE THREAD

**Issue by lazar725** [edcarroll/ng2-semantic-ui#367]
I'm trying to find an example of changing the default date format of ng2-sematic-ui datepicker, but unfortunately without success. For example, suppose I want the output to look like this: "1/03/2018".

Thanks.

**Comment by edcarroll** [comment]
Apologies for my slow reply, this is all doable via the [localization service](https://edcarroll.github.io/ng2-semantic-ui/#/behaviors/localization). You want to provide a custom format for the datepicker, then either inject that into the global service, or attach it to the datepicker instance.
