### ISSUE TITLE
Nothing New

### ISSUE THREAD

**Issue by simkepal** [edcarroll/ng2-semantic-ui#38]
Hello,

How is with this project. Nothing new now in quite some time...

**Comment by GFoley83** [comment]
Hi @edcarroll, would be good to an answer on this one please.

**Comment by edcarroll** [comment]
Hi, apologies for the lack of communication on my part. Essentially this project has been on temporary hold not only until I become less busy with work, but while the Angular 2 APIs calmed down and best practices began to emerge. I'm aiming to be able to do a bit more work on this in a few weeks, will update this issue if that changes 😃

**Comment by kentoj** [comment]
I am interested in contributing. If you wrote a contributors guide or a simple how to on how to take a semantic UI feature and port it to ng2-semantic-ui then I would like to follow that guide and contribute some code. Is that sort of a guide very likely to be written? I am not knowledgeable on reading and porting Semantic UI Javascript code from jQuery to Angular 2 though I would like to do so just to get a lot of experience and to make a great project (Ng2-semantic-ui) even greater.

**Comment by GregOnNet** [comment]
Hey there,

like @kentoj I am also interested to contribute to this project especially by fixing bugs or answering requests.

Kinds
Greg

**Comment by edcarroll** [comment]
Have just added the Popup component to 0.5.0, but am not planning on adding any further components until July due to unavoidable external commitments. Please do send me a gitter message however if you're interested in contributing still, as I would love to have people able to keep things ticking over / helping to answer any support requests.
