### ISSUE TITLE
Error with nested variable on labelField of sui-select component

### ISSUE THREAD

**Issue by dutrieux** [edcarroll/ng2-semantic-ui#381]
### Bug description:
Error with nested variable on labelField of sui-select component

### Link to minimally-working plunker that reproduces the issue:

https://stackblitz.com/edit/angular-dynzzd?file=src%2Fapp%2Fapp.component.html

### Version of Angular, ng2-semantic-ui, and Semantic UI:

Angular: 6.0.0

ng2-semantic-ui: 0.9.7

Semantic UI css : 2.3.1

**Comment by cossay** [comment]
I had the same problem today and spent more than three hours trying to find out what I was doing wrong. I managed to get it working by not using nested properties with labelField and labelValue.

**Comment by darckoune** [comment]
I had the same problem in my project. 
I really needed this feature, so I'll do my first pull request on a project \o/
