### ISSUE TITLE
Suggestion : Closing older resolved issues.

### ISSUE THREAD

**Issue by dev-fullstacktechnology** [edcarroll/ng2-semantic-ui#384]
### Request:
I have found some of older issues have been resolved but those are still in open category.
Right now I am seeing more then 80 issues in open list. It is causing bad reputation of this project.

Please someone can review all issues and close unnecessary or resolved points.

**Comment by dutrieux** [comment]
and 2 months without update, I thinks this project is dead :s

**Comment by rmundel** [comment]
I hope it's not dead. My project is counting on it 😭 
Even if it is, let's hear a confirmation of the owner to start an active fork.

**Comment by dev-fullstacktechnology** [comment]
The project is good and has been developed much since my first usage in angular 4+ project. Lets see what will happen next.

**Comment by dev-fullstacktechnology** [comment]
Project is dead. I pull my star back.
