### ISSUE TITLE
Vertical tab

### ISSUE THREAD

**Issue by genuinefafa** [edcarroll/ng2-semantic-ui#390]
I found out that semantic-ui supports something like vertical tabs. There is an example [here](https://semantic-ui.com/collections/menu.html#tabular).

Developing something that uses this setup will no be very DRY since the I'm using `sui-tabset`.

**Comment by avaneev95** [comment]
I think you can implement vertical tabs using the `sui-tabset` and `vertical` menu styles. Something like that:
```html
<sui-tabset>
<div class="ui grid">
  <div class="four wide column">
    <div class="ui secondary vertical pointing menu">
        <a class="item" suiTabHeader="1">First</a>
        <a class="item" suiTabHeader="2">Second</a>
        <a class="item" suiTabHeader="3">Third</a>
    </div>
  </div>
  <div class="twelve wide stretched column">
    <div class="ui segment">
        <div class="ui tab" suiTabContent="1">First tab!</div>
        <div class="ui tab" suiTabContent="2">Second tab!</div>
        <div class="ui tab" suiTabContent="3">Third tab!</div>
    </div>
  </div>
</div>
</sui-tabset>
```

**Comment by genuinefafa** [comment]
yea @avaneev95 you are right... it is somehow related with `css` set-up. Also, I did find some interesting things [here](https://semantic-ui.com/collections/menu.html#tabular) 

Thanks mate! Cheers.
