### ISSUE TITLE
Multi-select change "3 selection" placeholder

### ISSUE THREAD

**Issue by Al88** [edcarroll/ng2-semantic-ui#394]
Hi Mr Edward, greetings from Colombia!
This is not a bug, I just want to know if is there a way to change  placeholder "3 selections" on multi-select dropdown when user has selected some items
http://prntscr.com/k8kj8w

**Comment by rhefner** [comment]
+1 This would be very useful.

**Comment by edcarroll** [comment]
You can use the [localization service](https://edcarroll.github.io/ng2-semantic-ui/#/behaviors/localization) to edit the text shown in this case. Let me know if that doesn't cover it however!

**Comment by rhefner** [comment]
Hey @edcarroll:  Would be good to have this programmatic, no?  Similar to Selectize, where you could change the template vs. setting something that's semi-static like the localization service?  (unless I'm missing something, I don't know of a way to do this)
