### ISSUE TITLE
Jquery replacement

### ISSUE THREAD

**Issue by 4tron** [edcarroll/ng2-semantic-ui#4]
Considering the move away from jquery in most of the new frontend frameworks. could we maybe get some suggestions for alternatives. I guess one alternative would be to use css @keyframes and transitions. A lot of dog work though. Although there will be no reliance on any other library.

We could also use something like gsap : http://greensock.com/gsap .

Might be good to decide on an implementation to move forward with so that we can start on some of the semantic-ui module stuff.

**Comment by edcarroll** [comment]
I am considering converting the transitions component from the core semantic ui for Angular 2 - then using that to cover animations for all other components. I haven't taken too close a look at the transitions component but it seems the best way to go - what do you think? I also feel this is slightly lower priority as there are a few other important components to implement first - though I am keen to get your input on this :)

**Comment by 4tron** [comment]
I think transitions with @keyframes css animations might be the safest approved to keep consistency and more importantly not having to rely on another library.  This however is only supported from ie10 upwards which might be an issue. Gsap is super powerful ( maybe even to much so ) but then comes the question to we want to rely on another library for that. We couls could actually do some reallt cool stuff with gsap which might even take the angular2 semantic ui modules section to another level. 

Maybe at first we just release with transitions and then work from there. Very keen to start getting involved in the project . Will try fork asap and see what value i can add.

cheers going to to close the issue for now
