### ISSUE TITLE
sui.modal Incompatiple with Semantic UI CSS 2.3.3

### ISSUE THREAD

**Issue by TonyTNguyen** [edcarroll/ng2-semantic-ui#407]
I know the dependency require Semantic UI CSS 2.2.13, but fyi, the current sui.modal is not compatible to latest 2.3.3 due to changes in ui.modal of Semantic UI

**Comment by turgodi** [comment]
Might be a duplicate (https://github.com/edcarroll/ng2-semantic-ui/issues/371)
Workaround : override semantic-ui css with the previous css version for the modals only
`<link href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.1/semantic.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/components/modal.css" rel="stylesheet">`

**Comment by TonyTNguyen** [comment]
Work for me

**Comment by Vankerkom** [comment]
For people that come across this issue, install the alpha version where it is fixed.

`npm install ng2-semantic-ui@0.10.0-alpha.6`
