### ISSUE TITLE
sui-select remote data loading by clicking on it.

### ISSUE THREAD

**Issue by amandeep33** [edcarroll/ng2-semantic-ui#433]
I don't know if this is the right place to ask but I want this implementation:
**How can I load the data like this mentioned in sementic ui docs?
[https://semantic-ui.com/introduction/new.html#remote-data](url)**
_Remote Data
All dropdowns now support loading remote data. Selected name value pairs retrieved remotely are stored in sessionStorage so that selected values are repopulated correctly even after a page refresh._

`$.api.settings.api = {
  queryTags: '//api.semantic-ui.com/tags/{query}'
};

$('.ui.dropdown')
  .dropdown({
    apiSettings: {
      action: 'queryTags'
    }
  })
;`
**I want this in _ng2-sementic-ui_ way.**

**Comment by janpapenbrock** [comment]
Are you looking for **Remote Lookup** as explained here: https://edcarroll.github.io/ng2-semantic-ui/#/modules/select (section **Remote Lookup**)?
