### ISSUE TITLE
sui-select with reactive forms

### ISSUE THREAD

**Issue by mani0608** [edcarroll/ng2-semantic-ui#52]
@edcarroll  Sorry to bug you again with another query.

I am currently working with Angular 4 reactive forms. I have the following script inside html

```
<sui-select #select 
placeholder="Algorithms" 
[control]="algorithmMaster"
(selectedOptionsChange)="updateModel($event);"
[options]="algorithms"
labelField="displayName"
class="fluid">
```

But the [control] attribute is not working at all. Can you please confirm whether the attribute name [control] is correct. I am not sure whether this is a component issue.

**Comment by mani0608** [comment]
@edcarroll I got it working mate. I changed [control] to formControlName and it worked. 
But still when i first expand the dropdown, the default value which i pass through the formcontrol (algorithmMaster) is not highlighted/selected inside dropdown.

**Comment by edcarroll** [comment]
I've looked into your second issue and have fixed it on the develop branch. It will be included in the next release :)

**Comment by mani0608** [comment]
@edcarroll I need another help. Can you please add the formControlName attribute to the documentation when you find time. Because i have seen some components use their own attribute names instead. For e.g. as i have shown in my original post [control]. It would be really helpful for other users if its recorded in documentation. 
Thanks for all your support and for working on this awesome project. 👍

**Comment by edcarroll** [comment]
I've left it out of the documentation on purpose, because `formControlName` can be used wherever `ngModel` is supported - which I've documented on all appropriate components. If you think it would still be helpful to mention it on the docs, let me know and I can add it.

**Comment by mani0608** [comment]
Yes you are right. The default naming convention is "formControlName". One another project which I have come across for the same semantic components confused me. I hope others should be able to get it right like you said...

**Comment by edcarroll** [comment]
The fix for the default value not being selected is now live in `0.6.2`.

**Comment by mani0608** [comment]
@edcarroll Mate, i have successfully converted my project to Angular-CLI
Regarding the default value fix, for one object type it worked but for another it still not selected the option.

**Comment by ImTheC** [comment]
I had to add single quotes inside my double quotes:

`[formControlName]="'expire_month'"`

Should that be the case? Or am I missing something?

**Comment by ImTheC** [comment]
@edcarroll or @mani0608?

**Comment by edcarroll** [comment]
Sorry - completely missed this! When you say you had to add single quotes, were you initially trying `[formControlName]="expire_month"`?

If so, just writing `formControlName="expire_month"` should do the trick.

This is because `[]` syntax binds a variable to the property, whereas just writing the attribute treats it as a string literal.
