### ISSUE TITLE
How to use manual popup trigger

### ISSUE THREAD

**Issue by DrWifey** [edcarroll/ng2-semantic-ui#55]
I wanna show my popup only if some variable returns false (for example after checking that some element is empty), and as is written on a popup API description, we can use
`popupTrigger: Specifies the trigger for the popup. Available options are: hover, click, outsideClick, focus & manual`
But I can't figure out how to implement this.

**Comment by edcarroll** [comment]
The library only exposes functionality for manually calling `open`, `close`, and `toggle` on a popup, shown below. For more control, pass the `popup` variable into a function that does the conditional check you mentioned, again as shown below.

```html
<div class="ui segment" suiPopup popupText="Manual" popupTrigger="manual" #popup="suiPopup">
    <button class="ui button" (click)="popup.open()">Open!</button>
    <button class="ui button" (click)="openPopup(popup)">Conditionally Open!</button>
    <button class="ui button" (click)="popup.toggle()">Toggle!</button>
    <button class="ui button" (click)="popup.close()">Close!</button>
</div>
```

```ts
@Component({})
export class MyComponent {
    private _condition:boolean;

    public openPopup(popup:any) {
        if (this._condition) {
            popup.open();
        }
    }
}
```

Let me know if this answers your question!

**Comment by DrWifey** [comment]
Looks like this is what I need! Thank you
