### ISSUE TITLE
Accordion Component: ability to set the selector

### ISSUE THREAD

**Issue by Pennywise83** [edcarroll/ng2-semantic-ui#57]
Hi,
I think it would be nice if you can optionally declare the selector to activate the opening of the accordion.

In this way, for example, I could have a list of checkboxes and trigger the open action only to the arrow icon .

**Comment by edcarroll** [comment]
Hi, apologies for the slow response on this. In `0.6.5`, you're able to combine `isOpen` with `isDisabled` to have the desired effect. I've added an example to [the documentation](https://edcarroll.github.io/ng2-semantic-ui/#/components/accordion) to show how to do this.
