### ISSUE TITLE
ChangeDetectionStrategy.onPush Dropdown blinks

### ISSUE THREAD

**Issue by simkepal** [edcarroll/ng2-semantic-ui#59]
Hello,

I like your work very much. I just found out, if you use changeDetection: ChangeDetectionStrategy.onPush in component, so that angular doesn't check for changes on every click or mouse move, than dropdown does not work as it should. Can you please help me with this?

Thank you!

**Comment by edcarroll** [comment]
A fix for this is now live in `0.6.5`. Thank you @piotrn1 for providing the fix!
