### ISSUE TITLE
DropDown compiling issues (fix suggestion)

### ISSUE THREAD

**Issue by mmazloum** [edcarroll/ng2-semantic-ui#6]
At line 25 in components/dropdown.service.ts : 
    // State Events
    public onToggle:EventEmitter<boolean> = new EventEmitter(false);
    public isOpenChange:EventEmitter<boolean> = new EventEmitter(false);

Issues (at npm start) : 
Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<boolean>'.

Solution that fixes the problem : 
    // State Events
    public onToggle:EventEmitter<boolean> = new EventEmitter<boolean>(false);
    public isOpenChange:EventEmitter<boolean> = new EventEmitter<boolean>(false);

**Comment by edcarroll** [comment]
Hey, those code examples are the same, did you mean to paste something else? :) Will have a look into this tomorrow when I get some free time!

**Comment by mmazloum** [comment]
Sorry I meant : 
public onToggle:EventEmitter<boolean> = new EventEmitter**<boolean>**(false);
public isOpenChange:EventEmitter<boolean> = new EventEmitter**<boolean>**(false);

;-)

Take your time it is just to help, thanks a lot.

**Comment by mmazloum** [comment]
sorry I meant : 
`    // State Events
    public onToggle:EventEmitter<boolean> = new EventEmitter<boolean>(false);
    public isOpenChange:EventEmitter<boolean> = new EventEmitter<boolean>(false);`

You are really fast at improving this package thanks a lot, if you need help for these minor fixes, tell me, I'm new to angular 2 but I can handle this.

**Comment by elestedt** [comment]
I am seeing this in multiple places - compiler is complaining that the type of EventEmitter is not specified in new-statement, but in the type declaration for the property.

**Comment by edcarroll** [comment]
This is now fixed in 0.3.0. Sorry for the delay!
