### ISSUE TITLE
Module not found: Error: Can't resolve 'popper.js/dist/popper.es5

### ISSUE THREAD

**Issue by PrimeByDesign** [edcarroll/ng2-semantic-ui#60]
Hello, 

When trying to import a simple rating component as per your instructions on: 
https://edcarroll.github.io/ng2-semantic-ui/#/getting-started 
AND 
https://edcarroll.github.io/ng2-semantic-ui/#/components/rating

Note: I'm using Ng4 so it's possible that this library isn't ready for that yet. I did try looking for popper.js in npm but the package lacks a popper.es5.js file. 

Please help because I'm really looking forward to using your library! 

Thanks in advance.

See Error below: 

ERROR in ./~/ng2-semantic-ui/components/util/positioning.service.
js
Module not found: Error: Can't resolve 'popper.js/dist/popper.es5
.js' in '/Users/kiranrandhawa/Desktop/playground/ArtificialLab/no
de_modules/ng2-semantic-ui/components/util'
 @ ./~/ng2-semantic-ui/components/util/positioning.service.js 2:0
-50
 @ ./~/ng2-semantic-ui/components/popup/popup.directive.js
 @ ./~/ng2-semantic-ui/components/popup/popup.module.js
 @ ./~/ng2-semantic-ui/components/index.js
 @ ./~/ng2-semantic-ui/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/ma
in.ts
webpack: Failed to compile.

**Comment by PrimeByDesign** [comment]
I'm not sure why the above went strikethrough but it shouldn't be.

**Comment by mani0608** [comment]
@PrimeByDesign I get the same error when I try to build my app on a MAC OS. I am waiting for @edcarroll to return.

**Comment by PrimeByDesign** [comment]
@mani0608, Thanks, I am also using Mac Os. Have you used a replacement library?

**Comment by FezVrasta** [comment]
The way Popper.js is bundled changed in the latest versions.

You may fix it temporarily forcing to install the 1.5.* version of Popper.

To fix the bug here, the maintainer should make sure to import from one of the package.json entries, pkg.main or pkg.module

**Comment by PrimeByDesign** [comment]
Oh my goodness... I've been trying all evening. Thank you @FezVrasta!

**Comment by PrimeByDesign** [comment]
I was going to close this but actually the problem should be fixed so I have re-opened this issue.

**Comment by mani0608** [comment]
@PrimeByDesign and @FezVrasta I was actually including popper js as dependency before in my package.json
But, as per the confirmation from the developer that he has exported the module in the bundled file, I removed my dependency. And the build works well in Windows PC.
The problems occurs only when building on Mac OS.
@PrimeByDesign to answer your question, I'm currently using Windows and waiting for a fix or update from developer on issue with Mac OS.

**Comment by FezVrasta** [comment]
The problem is here:
https://github.com/edcarroll/ng2-semantic-ui/blob/38f15c672198ba11c3b69c0e47d74a41753580ea/components/util/positioning.service.ts#L3

the lib should simply import `popper.js`

**Comment by twotree** [comment]
I was showing the error: Module not found: Error: Can't resolve 'popper.js/dist/popper.es5.js' in 'C:\Code\vs\eubudu-s\node_modules\ng2-semantic-ui\components\util'

Worked fine when i changed the import to:
import Popper from 'popper.js/dist/popper-utils.js';

**Comment by mani0608** [comment]
This problem seems to be occurring on a windows OS too. Some of my team members facing this issue on windows OS, but it doesn't occur for me. Seems strange and we are all using the same package.json

**Comment by FezVrasta** [comment]
I think you just have to up delete node_modules and install over to get the error. By the way I already provided a solution.

**Comment by mani0608** [comment]
@FezVrasta Thanks mate. I did reinstall node_modules and received the error. I changed the import to popper.js and it worked.

**Comment by edcarroll** [comment]
This is now fixed in 0.6.3, thank you @FezVrasta for providing the fix.
