### ISSUE TITLE
Animation crashes upon attempt to insert dynamic data to Accordion

### ISSUE THREAD

**Issue by yavorskiy-web** [edcarroll/ng2-semantic-ui#61]
Hi. When trying to initialize an accordion with dynamic data, the animation is dropped. Here's an example of inserting data:

```
  <sui-accordion-panel *ngFor="let item of test.measurements_parameters | keys; let firstState = first;" [isOpen]="firstState">
    <div title>
      <i class="dropdown icon"></i>
      <accordion-title [category]="item"></accordion-title>
    </div>
    <div content>
      <accordion-content [parameters]="item.value"></accordion-content>
    </div>
  </sui-accordion-panel>
```
It's not so important how I get the data, but I'll just show that it happens dynamically:

```
 private getLatestTest(): void
  {
     this.testsService.getLatestTest().then(
       data =>
       {
          this.dataProcessing(data['_items'][0]);
       },
       error =>
       {
          this.errorProcessing(error);
       }
     );
  }
```
In order to double-check everything, I tried to change the data by clicking on the button:

```
<sui-accordion class="styled fluid">

  <sui-accordion-panel *ngFor="let item of dummyData">
    <div title>
      <i class="dropdown icon"></i>
      {{ item.propOne }}
    </div>
    <div content>
      {{ item.propTwo }}
    </div>
  </sui-accordion-panel>

</sui-accordion>

...

  onBtnClick()
  {
     this.fakeData = [ {propOne: 'anotherOne', propTwo: 'anotherTwo'}, {propOne: 'one', propTwo: 'two'} ];
  }
```

Behavior remains the same, animation crashes with dynamic data. How can I pass dynamic data to accordion? Now this is possible only with the help of resolvers, but this option does not quite fit me.

**Comment by edcarroll** [comment]
`0.6.5` now contains a fix for this - updating the values with `ngFor` no longer breaks the animation.

**Comment by NanoSpicer** [comment]
It looks like that in `0.9.7` the error with dynamical accordions with `*ngFor` is still there.
