### ISSUE TITLE
Cannot find type definition file for 'popper.js'

### ISSUE THREAD

**Issue by mani0608** [edcarroll/ng2-semantic-ui#64]
With the recent update 0.6.3,
when we try to build the application using angular-cli, we end up with the following errors,

`ERROR in D:/clement/install/openempi/mmmOnsite/web-component/src/main/resources/ 
node_modules/ng2-semantic-ui/components/util/positioning.service.d.ts (1,1): Can 
not find type definition file for 'popper.js'. `

`ERROR in D:/clement/install/openempi/mmmOnsite/web-component/src/main/resources/ 
node_modules/ng2-semantic-ui/components/popup/popup.d.ts (1,1): Cannot find type 
 definition file for 'popper.js'.`

For the time being i have reverted back to 0.6.2 with temporary fix.
Please help.

**Comment by edcarroll** [comment]
Have just released 0.6.4 onto npm, that includes a hotfix for this issue. Sorry for the inconvenience!

```bash
$ npm update ng2-semantic-ui
```
