### ISSUE TITLE
Cannot find type definition file for 'popper.js'.

### ISSUE THREAD

**Issue by Gmentsik** [edcarroll/ng2-semantic-ui#65]
On a fresh ng2 install and doing all the steps in the readme, I get this error when running ng build or ng serve:

`ERROR in S:/01.Git/java/microservice_skeleton/ui/jmss-ui/node_modules/ng2-semantic-ui/components/util/positioning.service.d.ts (1,1): Cannot find type definition file for 'popper.js'.
`

**Comment by yavorskiy-web** [comment]
Same problem:

ERROR in F:/Kolibri/frontend/node_modules/ng2-semantic-ui/components/util/positioning.service.d.ts (1,1): Cannot find type definition file for 'popper.js'.

**Comment by edcarroll** [comment]
Have just released 0.6.4 onto npm, that includes a hotfix for this issue. Sorry for the inconvenience!

```bash
$ npm update ng2-semantic-ui
```
