### ISSUE TITLE
Failed to load resource: the server responded with a status of 404

### ISSUE THREAD

**Issue by antoniorivera88** [edcarroll/ng2-semantic-ui#68]
I am triying to integrate Angular 2 with ng2SemanticUI library according to the Getting Started section but I have a compilation error:

`:3000/node_modules/rxjs/ Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:19 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/node_modules/rxjs
	Error: XHR error (404 Not Found) loading http://localhost:3000/node_modules/rxjs
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:1032:39)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:414:31)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:181:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:476:38)
	Error loading http://localhost:3000/node_modules/rxjs as "rxjs" from http://localhost:3000/node_modules/ng2-semantic-ui/bundles/ng2-semantic-ui.umd.min.js
	    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3000/node_modules/zone.js/dist/zone.js:1032:39)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:414:31)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:181:47)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:476:38)
	Error loading http://localhost:3000/node_modules/rxjs as "rxjs" from http://localhost:3000/node_modules/ng2-semantic-ui/bundles/ng2-semantic-ui.umd.min.js`

I have asked at [StackOverflow](http://stackoverflow.com/questions/43812503/angular-2-and-ng2semantic-compilation-error) but nobody has the solution.

**Comment by genuinefafa** [comment]
@antoniorivera88 it seems that the bundle `ng2-semantic-ui/bundles/ng2-semantic-ui.umd.min.js` references `require('rxjs')` which doesn't work.

It should be `require('rxjs/Rx')` according to the [rxjs docs](https://github.com/ReactiveX/RxJS#commonjs-via-npm) 

I'm not sure how to change that bundled file, maybe @edcarroll can help us out here. I'm having the same issue, change manually the file and it did start without the 404 error.

**Comment by edcarroll** [comment]
I think I might have managed to make it work - could you try the attached bundle (swap the files) and run again?

[ng2-semantic-ui.umd.min.zip](https://github.com/edcarroll/ng2-semantic-ui/files/1015863/ng2-semantic-ui.umd.min.zip)

**Comment by antoniorivera88** [comment]
Problem solved @edcarroll but **[isSearchable]** is not working for me. Is this related?

**Comment by edcarroll** [comment]
I'm not sure - in what way isn't it working? Could you post some sample code so I can take a look please?

**Comment by antoniorivera88** [comment]
Items are not being filtered acording to the user input. I have an AppComponent with it is template and an Member type.

**AppComponent**

`import { Component } from '@angular/core';
import {Member} from './member.type';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
})
export class AppComponent  {
  private Members: Array<Member>;

  constructor() {
    this.Members = new Array<Member>();
    this.Members.push(new Member('Evan', 'evan@mydomain.com'));
    this.Members.push(new Member('Samantha', 'samantha@mydomain.com'));
    this.Members.push(new Member('Elliot', 'elliot@mydomain.com'));
    this.Members.push(new Member('Susan', 'susan@mydomain.com'));
  }
}
`
**Member type**

'export class Member {
    private Name: string;
    private Login: string;

    constructor(Name: string, Login: string) {
        this.Name = Name;
        this.Login = Login;
    }
}'

**HTML Template**
** <sui-select [(ngModel)]="selectedMember" labelField="Name" #membersSelect [isSearchable]="true">
        <sui-select-option *ngFor="let member of Members" [value]="member"></sui-select-option>
    </sui-select>**

Thanks. I am really interested at integrating your modules on my project.

**Comment by edcarroll** [comment]
Sorry for the delay getting back to you! So the issue with your code is that you're not making use of `membersSelect.availableOptions`. In order to search through the results, the select needs to know what options are available - so you need to set `options` to `Members` and the `ngFor` needs to use `availableOptions`.

Your HTML should look like this:
```html
<sui-select [(ngModel)]="selectedMember" labelField="Name" [options]="Members" #membersSelect [isSearchable]="true">
    <sui-select-option ngFor="let member of membersSelect.availableOptions" [value]="member"></sui-select-option>
</sui-select>
```

Let me know however if that doesn't sort things for you.

**Comment by edcarroll** [comment]
`0.6.5` now contains the fix for the 404 error. As above, give me a shout if my code above doesn't sort the `[isSearchable]` issue.
