### ISSUE TITLE
Close select when opening another select

### ISSUE THREAD

**Issue by qoopa** [edcarroll/ng2-semantic-ui#71]
Hi! 

When having multiple select components on the same page it would be nice if they close when opening another one. Or have an option to that.

Thx for a great project

**Comment by edcarroll** [comment]
`0.6.5` is now live and has a fix included for this issue. I've essentially swapped all usages of `stopPropagation` with less intrusive alternatives, so click events and the like are no longer blocked by select, search & dropdown components.
