### ISSUE TITLE
Value from dropdown?

### ISSUE THREAD

**Issue by toeknee581** [edcarroll/ng2-semantic-ui#74]
I can't seem to find any way to get the selected value of the selected item of a dropdown.  It doesn't have a controlvalueaccessor, so you can't use ngModel.  Any thoughts?

**Comment by edcarroll** [comment]
In this project, a dropdown that returns a value is called a `select` - which has a `ControlValueAccessor` so can be used with `ngModel`.

**Comment by toeknee581** [comment]
thanks for the reply.  I've been working with it and I can't seem to get labels to be different from the value.  For instance, I have an object array with an id and a name field, but I can only get one or the other.  I want the value to be id and the text of the option to be name.  Any help would be very much appreciated.  I have tried things like this:

<sui-select (selectedOptionChange)="filterChange($event)" [options]="partnerList" [labelField]="options?.name" [valueField]="options?.id"
      #select>
      <sui-select-option *ngFor="let option of select.availableOptions" [value]="option.id">{{option.name}}</sui-select-option>
    </sui-select>

**Comment by edcarroll** [comment]
Apologies for the slow reply! The issue is your use of the `[]` syntax - in this case, both `labelField` and `valueField` are expecting a string path to the property in question. So, your code should look like this:

```html
<sui-select (selectedOptionChange)="filterChange($event)" [options]="partnerList" labelField="name" valueField="id"
#select>
    <sui-select-option *ngFor="let option of select.availableOptions" [value]="option"></sui-select-option>
</sui-select>
```
