### ISSUE TITLE
Implementation of Modal Component

### ISSUE THREAD

**Issue by edcarroll** [edcarroll/ng2-semantic-ui#78]
The final major component missing from this library is a modal component.

I'm opening this issue as I am now starting work on it, so will be updating things here.

**Comment by VladimirMakaev** [comment]
@edcarroll Looking forward to this one. We're planning to migrate to your library from ng-semantic and this is one of the components we're actively using. Let me know if you need any help

**Comment by edcarroll** [comment]
I've finished up writing the modal component, next it just needs a few finishing touches, some documentation and testing then it will be good to go.

The modal system is designed to be as flexible as possible: each modal has two possible outcomes, `approve` or `deny`, carrying a distinct result respectively, which is defined by the user. Transitions are built in, and fully customisable, and timing is handled out of the box as well (i.e. events don't fire until the modal has finished transitioning).

When creating the modals themselves, there are 2 different ways of doing it:

1. Automatic Modals
2. Advanced Modals
    a. Template
    b. Component

I've gone into detail about how to do that below.

----

#### Automatic Modals

These are the most simple form of modal dialog. They are created and used by adding a `<sui-modal>` element to your component. An example is below:

```html
<sui-modal [isClosable]="true" (dismiss)="alert($event)" #modal>
    <div class="header">Example</div>
    <div class="content">
        <p>Modal content</p>
    </div>
    <div class="actions">
        <button class="ui red button" (click)="modal.deny()">Cancel</button>
        <button class="ui green button" (click)="modal.approve('done')">OK</button>
    </div>
</sui-modal>
```

Options include `isClosable`, `size`, `transition` and more. Creating an inline variable is how to access the modal methods from within the component, so in this case `#modal` enables `modal.deny()` and `modal.approve('done')`.

Automatic modals are named as such because they open as soon as the component is rendered - there isn't any direct control about when they open. The specific use case for this type of modal are routes where the route opens up a modal dialog - set the route to be a component with an automatic modal and it will open immediately. You can then set the router to navigate when the `dismiss` event fires, for example `(dismiss)="router.navigate([])"`.

#### Advanced Modals

Advanced modals are what people will be using most of the time. These modals allow you to define either a template or entire component which becomes the content of the modal. They're opened by a `SuiModalService`, which provides the ability to open a modal on the page.

##### Using a template

This is the entire process for creating a template based modal. First, write your template as follows, using `let-context` and `let-modal="modal"` to access the context, and controls respectively.

```html
<ng-template let-context let-modal="modal" #modalTemplate>
    <div class="header">Example</div>
    <div class="content">
        <p>Modal content</p>
    </div>
    <div class="actions">
        <button class="ui red button" (click)="modal.deny('deny')">Cancel</button>
        <button class="ui green button" (click)="modal.approve('approve')">OK</button>
    </div>
</ng-template>
```

Next, you need to get access to your template from your component class, and ensure you have loaded the modal service:

```typescript
import {SuiModalService, TemplateModalConfig, ModalTemplate} from "ng2-semantic-ui";

@Component({})
export class MyComponent {
@ViewChild('modalTemplate')
    public modalTemplate:ModalTemplate<null, string, string>

    constructor(public modalService:SuiModalService) {}
}
```

Note, the 3 generic parameters for `ModalTemplate` are: 1) the context type (usually just an interface), 2) the `approve` result type, 3) the `deny` result type. In this case, we don't make use of a context object, and the modal itself passes string arguments to both `approve` and `deny`.

Finally, you can open your modal as follows:

```typescript
public open() {
    const config = new TemplateModalConfig<null, string, string>(this.modalTemplate);

    this.modalService
        .open(config)
        .onApprove(() => { /* approve callback */ }) 
        .onDeny(() => { /* deny callback */});
}
```

Template based modals are excellent for when you have a one-off UI that needs to appear, and won't be reused (as it isn't easy to share templates).

##### Using a component

Component based modals are by far the most powerful type of modal. They provide a way to generate generic modals for your entire application with minimal effort, for example to easily replace `prompt`, `alert` & `confirm` calls.

In the example below you will see how to create a generic Accept / Reject modal, and how easy it is to then reuse.

The first step is making a component that acts as the modal content. For this, you need to define the interface for the context (data passed into the modal when opened), as well as including `SuiModal` in the constructor - which is automatically injected into the component when it is generated and allows access to the `approve` and `deny` methods, as well as the aforementioned context.

```typescript
import {SuiModal, ComponentModalConfig, ModalSize} from "ng2-semantic-ui";

interface IAcceptRejectModalContext {
    title:string;
    question:string;
}

@Component({
    selector: 'modal-accept-reject',
    template: `
<div class="header">{{ modal.context.title }}</div>
<div class="content">
    <p>{{ modal.context.question }}</p>
</div>
<div class="actions">
    <button class="ui red button" (click)="modal.deny()">Cancel</button>
    <button class="ui green button" (click)="modal.approve()">OK</button>
</div>
`
})
export class AcceptRejectModalComponent {
    constructor(public modal:SuiModal<IAcceptRejectModalContext, void, void>) {}
}
````
Now that the content component is set up, you need to add it to your `entryComponents` in the `NgModule`, as otherwise Angular won't let you generate it.

Next, you define a helper class that automatically configures all new modals of this type:

```typescript
export class AcceptRejectModal extends ComponentModalConfig<IAcceptRejectModalContext, void, void> {
    constructor(title:string, question:string) {
        super(AcceptRejectModalComponent, { title, question }, false);

        this.transitionDuration = 200;
        this.size = ModalSize.Small;
    }
}
```

And that's all there is to it! To then use this new type of modal, do the following:

```typescript
const modal = new AcceptRejectModal("Are you sure?", "Are you sure about accepting this?");

this.modalService
    .open(modal)
    .onApprove(() => alert("accepted!"))
    .onDeny(() => alert("denied!"));
```

This will create the modal on the page, and will fire the provided events when the user clicks OK or cancel.

-------

I'd love some feedback on this system, general thoughts / criticisms are all great 😄 This doesn't have a few of the features (like the ability to externally control modals and a few other things) but the docs will have more when written.

Otherwise, as mentioned at the start of this huge post, I'll be releasing it in a few days in `0.8.0`.

**Comment by mcosta74** [comment]
@edcarroll, Great news

I have a project based on Bootstrap and I want to migrate to semantic-ui. Your library is fantastic but I really need modals to have a complete (and less painful) porting

**Comment by edcarroll** [comment]
Modals are now live in `0.8.0`. Head over to the [modal docs](https://edcarroll.github.io/ng2-semantic-ui/#/components/modal) for an explanation on how to integrate them into your applications.

If you have any issues or queries with the new modals please open a new issue rather than doing it here, now that they're released.
