### ISSUE TITLE
Upgrade to rc4

### ISSUE THREAD

**Issue by denodaeus** [edcarroll/ng2-semantic-ui#8]
Can you upgrade the project to rc4?  Current usage with anything > rc1 breaks because paths are not right in your build script for @angular/core.

For some reason this is breaking the accordion directive usage on an upgrade.  I tried making a fork and upgrading myself, but I haven't had a lot of luck since a lot of the libraries you depend on haven't been updated themselves.

**Comment by edcarroll** [comment]
Sorry for the massive delay on this - I decided to wait for Angular to become more stable before doing a proper upgrade. The project is now fully compatible with rc5, see the updated readme and docs :)
