### ISSUE TITLE
binding input/keypress to isSearchable select

### ISSUE THREAD

**Issue by DrWifey** [edcarroll/ng2-semantic-ui#80]
I'm trying to fire some events when user starts typing on isSearchable select and it works but it allows typing only one symbol and input clears immediately after first character typing... Is it okay?

```
<sui-select [(ngModel)]="selectedJobName"
                            [options]="criteriaSatisfiableJobs"
                            labelField="jobName"
                            [optionTemplate]="optionTemplate"
                            [placeholder]="'Type keyword'"
                            [noResultsMessage]="'To view available jobs, type some keyword'"
                            (keypress)="addJobsToList()"
                            [isSearchable]="true" #select>

                    <sui-select-option *ngFor="let option of select.availableOptions"
                                       [value]="option"></sui-select-option>
</sui-select>
```

**Comment by edcarroll** [comment]
From the looks of things, you're adding jobs to the list as the user types, is that correct?

**Comment by DrWifey** [comment]
I'm really sorry, it was my mistake :|

**Comment by edcarroll** [comment]
No worries! Glad you got it sorted 😄

**Comment by DrWifey** [comment]
Sorry, I can't now figure out if using a template while building <select-option> along with is searchable if I use 3 field, does search goes only through labelField value?
Because if I write some keyword that exists in path field for example and not exists in jobName, I'm getting 'no results' message.

```
<template class="" let-option #optionTemplate>
            <span class="select job name">{{ option.jobName }}</span>
            <span class="select job path">{{ option.jobPath }}</span>
            <span class="select job login">{{ option.jobCreatorLogin }}</span>
        </template>
        <div class="ui form">
            <div class="field">
                <sui-select [(ngModel)]="selectedJobObj"
                            (selectedOptionChange)="setSelectedJobName()"
                            (keypress)="addJobsToList()"
                            [options]="criteriaSatisfiableJobs"
                            labelField="jobCreatorLogin"
                            [optionTemplate]="optionTemplate"
                            [placeholder]="'Type keyword'"
                            [noResultsMessage]="'To view available jobs, type some keyword'"
                            [isSearchable]="true" #select>

                    <sui-select-option *ngFor="let option of select.availableOptions"
                                       [value]="option"></sui-select-option>
                </sui-select>
            </div>
        </div>
```

**Comment by edcarroll** [comment]
Correct, when searching with a select, only the value of the `labelField` is used for the search. When using a template, you must still provide a `labelField` so the search can happen.

I wonder if it would be helpful to be able to define a custom search function, separate from a remote lookup? (so you could search on multiple fields).

**Comment by DrWifey** [comment]
How can I do that? Bind custom search function to input event?

**Comment by edcarroll** [comment]
You can't currently - but it sounds like it would be helpful! I can work on getting something like that included in the next release?

**Comment by edcarroll** [comment]
Actually, in this case, Use a function `lookupFn:(query:string) => Promise<Job[]>` for `[options]` like in the docs, something like:

```typescript
@Component({})
export class MyComponent {
    public criteriaSatisfiableJobs:Job[] = [...];
    public jobsLookup = (query:string) => {
        return new Promise(resolve => {
            if (query == "") {
                resolve(this.criteriaSatisfiableJobs);
            }
            // Do the extended lookup on multiple fields manually here:
            resolve(this.criteriaSatisfiableJobs.filter(j => ...));
        }
    }
}
```

```html
<sui-select ... [options]="jobsLookup" ... >
```

Does that make sense?

**Comment by DrWifey** [comment]
It would be great if such future appears as "out-of-the-box", but so far I guess I'll try to use some npm module like `ng2-completer` or something like this else. Thanks a lot!

**Comment by edcarroll** [comment]
I've just opened #85, which goes some way to making this situation easier - I think outside of that relying on external modules for more advanced searching is sensible, as it unnecessarily clutters this library. Thoughts? 😄
