### ISSUE TITLE
Bug when calculating the height of the accordion panels

### ISSUE THREAD

**Issue by yavorskiy-web** [edcarroll/ng2-semantic-ui#81]
This request is especially relevant when viewing applications on mobile devices. When the width of the window is reduced or the orientation of the device changes, the accordion does not recalculate the height and content will be placed on top of each other.

To be sure that this is not an error in styles, I сhecked this behavior on semantic-ui.com.

Add screenshots (left: sui-semantic, right: semantic):

---------------------------------------------------------------------------------------------

![1](https://cloud.githubusercontent.com/assets/19890852/26682310/b91e809e-46e8-11e7-97bd-1982b7caadba.jpg)

---------------------------------------------------------------------------------------------

![2](https://cloud.githubusercontent.com/assets/19890852/26682318/be6866be-46e8-11e7-914b-951f65d42787.jpg)

**Comment by edcarroll** [comment]
This looks to be an issue with the collapse - will work in a fix for the next release.

**Comment by edcarroll** [comment]
The fix for this is now live in `0.8.0` 😄
