### ISSUE TITLE
Integrate with system js example

### ISSUE THREAD

**Issue by johndiego** [edcarroll/ng2-semantic-ui#9]
Sorry guys!!
I am newbie in angular2.
How i can integrate with in my code?
Att.

`(function (global) {

  // map tells the System loader where to look for things
  var map = {
    'angular2-jwt': 'node_modules/angular2-jwt/angular2-jwt.js',
    'app': 'app', // 'dist',
// I Try
//    'ng2-semantic-ui': 'node_modules/ng2-semantic-ui',
    'rxjs': 'node_modules/rxjs',
    'symbol-observable': 'node_modules/symbol-observable',
    '@angular': 'node_modules/@angular',

  };

  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app': { main: 'boot.js', defaultExtension: 'js' },
    'rxjs': { defaultExtension: 'js' },
    'symbol-observable': { main: 'index.js', defaultExtension: 'js' }
  };

  var packageNames = [
    '@angular/common',
    '@angular/compiler',
    '@angular/core',
    '@angular/http',
    '@angular/platform-browser',
    '@angular/platform-browser-dynamic',
    '@angular/router'
  ];

  // add package entries for angular packages in the form '@angular/common': { main: 'index.js', defaultExtension: 'js' }
  packageNames.forEach(function (pkgName) {
    packages[pkgName] = { main: 'index.js', defaultExtension: 'js' };
  });

  var config = {
    map: map,
    packages: packages
  }

  // filterSystemConfig - index.html's chance to modify config before we register it.
  if (global.filterSystemConfig) { global.filterSystemConfig(config); }

  System.config(config);

})(this);`

this is my error...

http://localhost:3000/node_modules/ng2-semantic-ui/ng2-semantic-ui Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:16 Error: Error: XHR error (404 Not Found) loading http://localhost:3000/node_modules/ng2-semantic-ui/ng2-semantic-ui(…)

Thanks for advanced

**Comment by edcarroll** [comment]
Hi there, sorry for the delayed reply! If you still would like to use the project I recommend updating to the latest version (0.3.0) as it supports webpack and angular rc5 (see updated docs). Thanks!
